/* GENERATED by scripts/build-equipment.mjs. Do not edit by hand.
 *
 * What every exercise is done on, read off the props its animation is drawn
 * with, so the machine named here is the machine in the picture. Regenerate
 * after changing any move's props:
 *
 *   node scripts/build-equipment.mjs
 *
 * `kit` is what you have to find; `setup` is how to set it up once you are
 * standing at it. An empty kit means bodyweight, nothing to fetch.
 */

export const KIT = {
  "lat-pulldown": { label: "Lat pulldown machine", group: "machine" },
  "seated-row": { label: "Seated row machine", group: "machine" },
  "chest-press": { label: "Chest press machine", group: "machine" },
  "shoulder-press": { label: "Shoulder press machine", group: "machine" },
  "pec-deck": { label: "Pec deck", group: "machine" },
  "leg-extension": { label: "Leg extension machine", group: "machine" },
  "leg-curl": { label: "Leg curl machine", group: "machine" },
  "leg-press": { label: "Leg press machine", group: "machine" },
  "hack-squat": { label: "Hack squat machine", group: "machine" },
  "seated-calf": { label: "Seated calf machine", group: "machine" },
  "reverse-hyper": { label: "Reverse hyper machine", group: "machine" },
  "ghd": { label: "Glute-ham developer", group: "machine" },
  "back-extension": { label: "Back extension bench", group: "machine" },
  "cable": { label: "Cable machine", group: "machine" },
  "cable-crossover": { label: "Cable crossover", group: "machine" },
  "landmine": { label: "Landmine", group: "machine" },
  "smith-machine": { label: "Smith machine", group: "machine" },
  "attach-bar": { label: "Straight bar attachment", group: "attachment" },
  "attach-lat": { label: "Wide lat bar", group: "attachment" },
  "attach-vbar": { label: "V-bar attachment", group: "attachment" },
  "attach-rope": { label: "Rope attachment", group: "attachment" },
  "attach-handle": { label: "Single handle", group: "attachment" },
  "attach-strap": { label: "Ankle strap", group: "attachment" },
  "bench": { label: "Flat bench", group: "bench" },
  "bench-adjustable": { label: "Adjustable bench", group: "bench" },
  "preacher-bench": { label: "Preacher bench", group: "bench" },
  "pullup-bar": { label: "Pull-up bar", group: "station" },
  "dip-bars": { label: "Dip bars", group: "station" },
  "parallettes": { label: "Parallettes", group: "station" },
  "box": { label: "Box or step", group: "station" },
  "calf-block": { label: "Calf block", group: "station" },
  "rack": { label: "Rack", group: "station" },
  "rig-post": { label: "Upright post", group: "station" },
  "wall": { label: "A wall", group: "station" },
  "doorway": { label: "A doorway", group: "station" },
  "barbell": { label: "Barbell", group: "free" },
  "ez-bar": { label: "EZ bar", group: "free" },
  "dumbbell": { label: "Dumbbells", group: "free" },
  "dumbbell-one": { label: "One dumbbell", group: "free" },
  "kettlebell": { label: "Kettlebell", group: "free" },
  "plate": { label: "Weight plate", group: "free" },
  "dip-belt": { label: "Dip belt", group: "free" },
  "band": { label: "Resistance band", group: "small" },
  "roller": { label: "Foam roller", group: "small" },
  "ab-wheel": { label: "Ab wheel", group: "small" },
  "block": { label: "Yoga block", group: "small" },
  "mat": { label: "Mat", group: "small" },
};

export const EQUIPMENT = {
  "90/90 Hip Switch": { kit: ["mat"], setup: [] },
  "Ab Wheel Rollout": { kit: ["ab-wheel", "mat"], setup: [] },
  "Ankle Circles": { kit: [], setup: [] },
  "Archer Pull-Up": { kit: ["pullup-bar"], setup: [] },
  "Archer Push-Up": { kit: [], setup: [] },
  "Arm Circles": { kit: [], setup: [] },
  "Arnold Press": { kit: ["bench-adjustable", "dumbbell"], setup: ["Seat upright"] },
  "Back Extension": { kit: ["back-extension"], setup: [] },
  "Band Pull-Apart": { kit: ["band"], setup: [] },
  "Band Shoulder External Rotation": { kit: ["band"], setup: [] },
  "Barbell Back Squat": { kit: ["rack", "barbell"], setup: [] },
  "Barbell Bench Press": { kit: ["bench", "barbell"], setup: [] },
  "Barbell Curl": { kit: ["barbell"], setup: [] },
  "Barbell Row": { kit: ["barbell"], setup: [] },
  "Barbell Shrug": { kit: ["barbell"], setup: [] },
  "Behind-the-Back Shrug": { kit: ["barbell"], setup: [] },
  "Bench Dip": { kit: ["bench"], setup: [] },
  "Bent-Knee Calf Stretch": { kit: ["wall"], setup: [] },
  "Biceps Wall Stretch": { kit: ["wall"], setup: [] },
  "Bird Dog": { kit: ["mat"], setup: [] },
  "Boat Pose": { kit: ["mat"], setup: [] },
  "Bodyweight Squat": { kit: [], setup: [] },
  "Boomerang": { kit: ["mat"], setup: [] },
  "Bridge": { kit: ["mat"], setup: [] },
  "Bridge Pose": { kit: ["mat"], setup: [] },
  "Bulgarian Split Squat": { kit: ["bench"], setup: [] },
  "Butterfly Pose": { kit: ["mat"], setup: [] },
  "Cable Crunch": { kit: ["cable", "attach-rope"], setup: [] },
  "Cable Curl": { kit: ["cable", "attach-bar"], setup: [] },
  "Cable Fly": { kit: ["cable-crossover", "attach-handle"], setup: [] },
  "Cable Kickback": { kit: ["cable", "attach-strap"], setup: [] },
  "Cable Lateral Raise": { kit: ["cable", "attach-handle"], setup: [] },
  "Cable Pull-Through": { kit: ["cable", "attach-rope"], setup: [] },
  "Camel Pose": { kit: ["mat"], setup: [] },
  "Cat-Cow": { kit: ["mat"], setup: [] },
  "Chair Pose": { kit: [], setup: [] },
  "Chest-Supported Row": { kit: ["bench-adjustable", "dumbbell"], setup: ["Bench on incline, about 45 degrees", "Lie face down on the pad"] },
  "Child's Pose": { kit: ["mat"], setup: [] },
  "Chin Tucks": { kit: [], setup: [] },
  "Chin-Up": { kit: ["pullup-bar"], setup: [] },
  "Clamshell": { kit: ["mat"], setup: [] },
  "Close-Grip Bench Press": { kit: ["bench", "barbell"], setup: [] },
  "Close-Grip Pulldown": { kit: ["lat-pulldown", "attach-vbar"], setup: [] },
  "Cobra Pose": { kit: ["mat"], setup: [] },
  "Concentration Curl": { kit: ["bench", "dumbbell-one"], setup: [] },
  "Control Balance": { kit: ["mat"], setup: [] },
  "Corkscrew": { kit: ["mat"], setup: [] },
  "Corpse Pose (Savasana)": { kit: ["mat"], setup: [] },
  "Cossack Squat": { kit: [], setup: [] },
  "Couch Stretch": { kit: ["wall", "mat"], setup: [] },
  "Criss-Cross": { kit: ["mat"], setup: [] },
  "Cross-Body Arm Swings": { kit: [], setup: [] },
  "Cross-Body Shoulder Stretch": { kit: [], setup: [] },
  "Crow Pose": { kit: ["mat"], setup: [] },
  "Crunch": { kit: ["mat"], setup: [] },
  "Cuban Press": { kit: ["dumbbell"], setup: [] },
  "Curtsy Lunge": { kit: ["dumbbell"], setup: [] },
  "Dancer's Pose": { kit: [], setup: [] },
  "Dead Hang": { kit: ["pullup-bar"], setup: [] },
  "Deadlift": { kit: ["barbell"], setup: [] },
  "Decline Barbell Press": { kit: ["bench-adjustable", "barbell"], setup: ["Bench on decline, about 25 degrees"] },
  "Decline Dumbbell Press": { kit: ["bench-adjustable", "dumbbell"], setup: ["Bench on decline, about 25 degrees"] },
  "Deep Squat Hold": { kit: [], setup: [] },
  "Diamond Push-Up": { kit: [], setup: [] },
  "Dip": { kit: ["dip-bars"], setup: [] },
  "Donkey Calf Raise": { kit: ["bench", "calf-block"], setup: [] },
  "Doorway Pec Stretch": { kit: ["doorway"], setup: [] },
  "Double Leg Stretch": { kit: ["mat"], setup: [] },
  "Downward-Facing Dog": { kit: ["mat"], setup: [] },
  "Dumbbell Bench Press": { kit: ["bench", "dumbbell"], setup: [] },
  "Dumbbell Calf Raise": { kit: ["dumbbell-one"], setup: [] },
  "Dumbbell Curl": { kit: ["dumbbell"], setup: [] },
  "Dumbbell Row": { kit: ["bench", "dumbbell-one"], setup: [] },
  "Dumbbell Shoulder Press": { kit: ["dumbbell"], setup: [] },
  "Dumbbell Shrug": { kit: ["dumbbell"], setup: [] },
  "EZ-Bar Curl": { kit: ["ez-bar"], setup: [] },
  "Eagle Pose": { kit: [], setup: [] },
  "Elbow Circles": { kit: [], setup: [] },
  "Extended Side Angle": { kit: [], setup: [] },
  "Face Pull": { kit: ["cable", "attach-rope"], setup: [] },
  "Farmer's Carry": { kit: ["dumbbell"], setup: [] },
  "Figure Four Stretch": { kit: ["mat"], setup: [] },
  "Firefly Pose": { kit: ["mat"], setup: [] },
  "Foam Roller Chest Opener": { kit: ["roller", "mat"], setup: [] },
  "Foam Roller Thoracic Extension": { kit: ["roller", "mat"], setup: [] },
  "Forward Fold": { kit: [], setup: [] },
  "Freestanding Handstand": { kit: [], setup: [] },
  "Frog Pump": { kit: ["mat"], setup: [] },
  "Frog Stretch": { kit: ["mat"], setup: [] },
  "Front Lever": { kit: ["pullup-bar"], setup: [] },
  "Front Raise": { kit: ["dumbbell"], setup: [] },
  "Front Squat": { kit: ["rack", "barbell"], setup: [] },
  "Full Planche": { kit: [], setup: [] },
  "Glute Bridge": { kit: ["mat"], setup: [] },
  "Glute-Ham Raise": { kit: ["ghd"], setup: [] },
  "Goblet Squat": { kit: ["dumbbell-one"], setup: [] },
  "Good Morning": { kit: ["rack", "barbell"], setup: [] },
  "Hack Squat": { kit: ["hack-squat"], setup: [] },
  "Half Moon Pose": { kit: ["block"], setup: [] },
  "Half-Kneeling Hip Flexor Rock": { kit: ["mat"], setup: [] },
  "Hammer Curl": { kit: ["dumbbell"], setup: [] },
  "Handstand Push-Up": { kit: [], setup: [] },
  "Hanging Leg Raise": { kit: ["pullup-bar"], setup: [] },
  "Hanging Windshield Wiper": { kit: ["pullup-bar"], setup: [] },
  "Hip Circles": { kit: [], setup: [] },
  "Hip Thrust": { kit: ["bench", "barbell"], setup: [] },
  "Hollow Body Hold": { kit: [], setup: [] },
  "Human Flag": { kit: ["rig-post"], setup: [] },
  "Inchworm Walkout": { kit: [], setup: [] },
  "Incline Barbell Press": { kit: ["bench-adjustable", "barbell"], setup: ["Bench on incline, about 35 degrees"] },
  "Incline Dumbbell Curl": { kit: ["bench-adjustable", "dumbbell"], setup: ["Bench on incline, about 46 degrees"] },
  "Incline Dumbbell Press": { kit: ["bench-adjustable", "dumbbell"], setup: ["Bench on incline, about 35 degrees"] },
  "Incline Push-Up": { kit: ["bench"], setup: [] },
  "Inverted Row": { kit: ["pullup-bar"], setup: [] },
  "Jackknife": { kit: ["mat"], setup: [] },
  "King Pigeon Pose": { kit: ["mat"], setup: [] },
  "Knee-to-Wall Ankle Rock": { kit: ["wall"], setup: [] },
  "Kneeling Hip Flexor Stretch": { kit: ["mat"], setup: [] },
  "Kneeling Lat Stretch": { kit: ["bench"], setup: [] },
  "Knees-to-Chest Stretch": { kit: ["mat"], setup: [] },
  "L-Sit": { kit: ["parallettes"], setup: [] },
  "Landmine Press": { kit: ["landmine"], setup: [] },
  "Lat Pulldown": { kit: ["lat-pulldown", "attach-lat"], setup: [] },
  "Lateral Leg Swings": { kit: [], setup: [] },
  "Lateral Raise": { kit: ["dumbbell"], setup: [] },
  "Leg Circles": { kit: ["mat"], setup: [] },
  "Leg Curl": { kit: ["leg-curl"], setup: [] },
  "Leg Extension": { kit: ["leg-extension"], setup: [] },
  "Leg Press": { kit: ["leg-press"], setup: [] },
  "Leg Press Calf Raise": { kit: ["leg-press"], setup: [] },
  "Leg Swings": { kit: [], setup: [] },
  "Legs-Up-the-Wall Pose": { kit: ["wall"], setup: [] },
  "Lizard Pose": { kit: ["mat"], setup: [] },
  "Low Lunge": { kit: ["mat"], setup: [] },
  "Low-to-High Cable Fly": { kit: ["cable", "attach-handle"], setup: [] },
  "Machine Chest Press": { kit: ["chest-press"], setup: [] },
  "Machine Shoulder Press": { kit: ["shoulder-press"], setup: [] },
  "Mountain Pose": { kit: [], setup: [] },
  "Muscle-Up": { kit: ["pullup-bar"], setup: [] },
  "Negative Pull-Up": { kit: ["pullup-bar"], setup: [] },
  "Nordic Curl": { kit: [], setup: [] },
  "One-Arm Pull-Up": { kit: ["pullup-bar"], setup: [] },
  "One-Arm Push-Up": { kit: [], setup: [] },
  "Open Book Thoracic Rotation": { kit: ["mat"], setup: [] },
  "Overhead Press": { kit: ["barbell"], setup: [] },
  "Overhead Triceps Extension": { kit: ["dumbbell-one"], setup: [] },
  "Overhead Triceps Stretch": { kit: [], setup: [] },
  "Pallof Press": { kit: ["cable", "attach-handle"], setup: [] },
  "Pec Deck": { kit: ["pec-deck"], setup: [] },
  "Pelvic Tilts": { kit: ["mat"], setup: [] },
  "Pendlay Row": { kit: ["barbell"], setup: [] },
  "Pigeon Pose": { kit: ["mat"], setup: [] },
  "Pistol Squat": { kit: [], setup: [] },
  "Planche Lean": { kit: [], setup: [] },
  "Plank": { kit: [], setup: [] },
  "Plank Pose": { kit: ["mat"], setup: [] },
  "Plate Pinch": { kit: ["barbell"], setup: [] },
  "Preacher Curl": { kit: ["preacher-bench", "ez-bar"], setup: [] },
  "Prone Press-Up": { kit: ["mat"], setup: [] },
  "Prone Scorpion Stretch": { kit: ["mat"], setup: [] },
  "Prone Y Raise": { kit: ["mat"], setup: [] },
  "Pseudo Planche Push-Up": { kit: [], setup: [] },
  "Pull-Up": { kit: ["pullup-bar"], setup: [] },
  "Push Press": { kit: ["barbell"], setup: [] },
  "Push-Up": { kit: [], setup: [] },
  "Quadruped Thoracic Rotation": { kit: ["mat"], setup: [] },
  "Quadruped Wrist Rocks": { kit: ["mat"], setup: [] },
  "Rear Delt Fly": { kit: ["dumbbell"], setup: [] },
  "Reclined Bound Angle Pose": { kit: ["mat"], setup: [] },
  "Reclined Twist": { kit: ["mat"], setup: [] },
  "Reverse Crunch": { kit: ["mat"], setup: [] },
  "Reverse Curl": { kit: ["barbell"], setup: [] },
  "Reverse Hyperextension": { kit: ["reverse-hyper"], setup: [] },
  "Reverse Pec Deck": { kit: ["pec-deck"], setup: [] },
  "Reverse Wrist Curl": { kit: ["bench", "dumbbell-one"], setup: [] },
  "Revolved Chair Pose": { kit: [], setup: [] },
  "Revolved Triangle": { kit: ["block"], setup: [] },
  "Roll-Over": { kit: ["mat"], setup: [] },
  "Roll-Up": { kit: ["mat"], setup: [] },
  "Romanian Deadlift": { kit: ["barbell"], setup: [] },
  "Rope Pushdown": { kit: ["cable", "attach-rope"], setup: [] },
  "Russian Twist": { kit: ["mat"], setup: [] },
  "Saw": { kit: ["mat"], setup: [] },
  "Scapular Push-Up": { kit: [], setup: [] },
  "Seated Cable Row": { kit: ["seated-row", "attach-vbar"], setup: [] },
  "Seated Calf Raise": { kit: ["seated-calf"], setup: [] },
  "Seated Dumbbell Press": { kit: ["bench-adjustable", "dumbbell"], setup: ["Seat upright"] },
  "Seated Spinal Twist": { kit: ["mat"], setup: [] },
  "Shoulder Bridge": { kit: ["mat"], setup: [] },
  "Shoulder Rolls": { kit: [], setup: [] },
  "Shrimp Squat": { kit: [], setup: [] },
  "Side Bend": { kit: ["dumbbell-one"], setup: [] },
  "Side Kick Series": { kit: ["mat"], setup: [] },
  "Side Plank": { kit: [], setup: [] },
  "Side-Lying Leg Lift": { kit: ["mat"], setup: [] },
  "Single Leg Stretch": { kit: ["mat"], setup: [] },
  "Single-Leg Calf Raise": { kit: ["calf-block"], setup: [] },
  "Single-Leg Romanian Deadlift": { kit: ["dumbbell-one"], setup: [] },
  "Sissy Squat": { kit: [], setup: [] },
  "Sit-Up": { kit: ["mat"], setup: [] },
  "Skull Crusher": { kit: ["bench", "barbell"], setup: [] },
  "Snatch-Grip High Pull": { kit: ["barbell"], setup: [] },
  "Sphinx Stretch": { kit: ["mat"], setup: [] },
  "Spider Curl": { kit: ["bench-adjustable", "dumbbell"], setup: ["Bench on incline, about 45 degrees", "Lie face down on the pad"] },
  "Spine Stretch Forward": { kit: ["mat"], setup: [] },
  "Split Squat": { kit: [], setup: [] },
  "Splits (Hanumanasana)": { kit: ["mat"], setup: [] },
  "Squat to Stand": { kit: [], setup: [] },
  "Standing Calf Raise": { kit: ["calf-block"], setup: [] },
  "Standing Calf Stretch": { kit: ["wall"], setup: [] },
  "Standing Forward Hang": { kit: [], setup: [] },
  "Standing Hamstring Stretch": { kit: [], setup: [] },
  "Standing Hip Airplane": { kit: [], setup: [] },
  "Standing Side Bend Stretch": { kit: [], setup: [] },
  "Step-Up": { kit: ["box", "dumbbell"], setup: [] },
  "Stiff-Leg Deadlift": { kit: ["dumbbell"], setup: [] },
  "Straight-Arm Band Pulldown": { kit: ["band"], setup: [] },
  "Straight-Arm Pulldown": { kit: ["cable", "attach-bar"], setup: [] },
  "Suitcase Carry": { kit: ["dumbbell-one"], setup: [] },
  "Sumo Deadlift": { kit: ["barbell"], setup: [] },
  "Superman": { kit: ["mat"], setup: [] },
  "Supine Hamstring Stretch": { kit: ["mat"], setup: [] },
  "Swan": { kit: ["mat"], setup: [] },
  "Swimming": { kit: ["mat"], setup: [] },
  "T-Bar Row": { kit: ["landmine"], setup: [] },
  "Teaser": { kit: ["mat"], setup: [] },
  "The Hundred": { kit: ["mat"], setup: [] },
  "Thread the Needle Stretch": { kit: ["mat"], setup: [] },
  "Toes-to-Bar": { kit: ["pullup-bar"], setup: [] },
  "Torso Twists": { kit: [], setup: [] },
  "Toy Soldier Kicks": { kit: [], setup: [] },
  "Tree Pose": { kit: [], setup: [] },
  "Triangle Pose": { kit: [], setup: [] },
  "Triceps Kickback": { kit: ["bench", "dumbbell-one"], setup: [] },
  "Triceps Pushdown": { kit: ["cable", "attach-bar"], setup: [] },
  "Tuck Front Lever": { kit: ["pullup-bar"], setup: [] },
  "Tuck L-Sit": { kit: ["parallettes"], setup: [] },
  "Tuck Planche": { kit: [], setup: [] },
  "Upper Trap Stretch": { kit: [], setup: [] },
  "Upright Row": { kit: ["barbell"], setup: [] },
  "Upward-Facing Dog": { kit: ["mat"], setup: [] },
  "V-Sit": { kit: ["parallettes"], setup: [] },
  "V-Up": { kit: ["mat"], setup: [] },
  "Walking Lunge": { kit: ["dumbbell"], setup: [] },
  "Walking Lunge with Twist": { kit: [], setup: [] },
  "Wall Handstand Hold": { kit: ["wall"], setup: [] },
  "Wall Hip Hinge Drill": { kit: ["wall"], setup: [] },
  "Wall Push-Up": { kit: ["wall"], setup: [] },
  "Wall Slides": { kit: ["wall"], setup: [] },
  "Warrior I": { kit: [], setup: [] },
  "Warrior II": { kit: [], setup: [] },
  "Warrior III": { kit: [], setup: [] },
  "Weighted Dip": { kit: ["dip-bars", "dip-belt", "plate"], setup: [] },
  "Weighted Pull-Up": { kit: ["pullup-bar", "dip-belt", "plate"], setup: [] },
  "Wheel Pose": { kit: ["mat"], setup: [] },
  "Woodchopper": { kit: ["cable", "attach-handle"], setup: [] },
  "World's Greatest Stretch": { kit: [], setup: [] },
  "Wrist Circles": { kit: [], setup: [] },
  "Wrist Curl": { kit: ["bench", "dumbbell-one"], setup: [] },
  "Wrist Extensor Stretch": { kit: [], setup: [] },
  "Wrist Flexor Stretch": { kit: [], setup: [] },
  "Zercher Squat": { kit: ["rack", "barbell"], setup: [] },
};

/* People and plans do not always use the library's full name: a plan can say
   "Bench Press" where the library says "Barbell Bench Press", and somebody
   typing their own exercise will write "bench press" or "Bench press".
   So: exact name, then the same name ignoring case and punctuation, then the
   ONE library name that ends with it. Ends with, not contains, because
   "Bench Press" is a bench press with a bar on it, while "Squat" could be six
   different lifts and a wrong machine is worse than no line at all. */
const NORM = new Map();
for (const n of Object.keys(EQUIPMENT)) {
  const k = n.toLowerCase().replace(/[^a-z0-9]+/g, "");
  if (!NORM.has(k)) NORM.set(k, n);
}
export function resolveName(name) {
  if (!name) return null;
  if (EQUIPMENT[name]) return name;
  const k = String(name).toLowerCase().replace(/[^a-z0-9]+/g, "");
  if (!k) return null;
  if (NORM.has(k)) return NORM.get(k);
  const hits = [];
  for (const [nk, full] of NORM) if (nk.endsWith(k)) hits.push(full);
  if (hits.length === 1) return hits[0];
  /* Several matched. A gym settles this the same way every time: the
     unqualified name means the barbell one. "Bench press" is the barbell
     bench press, "row" is the barbell row, and anything else gets said out
     loud ("dumbbell row"). So one barbell candidate wins; no barbell
     candidate, or two, and we say nothing rather than name the wrong kit. */
  const words = String(name).trim().split(" ").filter(Boolean).length;
  if (words < 2) return null;      // "Press" is not a lift, it is half of one
  const barbell = hits.filter((n) => n.startsWith("Barbell "));
  return barbell.length === 1 ? barbell[0] : null;
}
export function kitOf(name) {
  const key = resolveName(name);
  return key ? EQUIPMENT[key] : null;
}

/* Everything one session needs, biggest thing first, deduplicated, with the
   exercises that want each so a card can say why. */
export function kitForSession(names = []) {
  const order = ["machine","attachment","bench","station","free","small"];
  const by = new Map();
  for (const name of names) {
    for (const id of (kitOf(name) || {}).kit || []) {
      if (!by.has(id)) by.set(id, []);
      by.get(id).push(name);
    }
  }
  // A day that wants a pair somewhere already sends you to the rack, so the
  // single-bell line would just be a second trip for the same shelf.
  if (by.has("dumbbell") && by.has("dumbbell-one")) {
    by.get("dumbbell").push(...by.get("dumbbell-one"));
    by.delete("dumbbell-one");
  }
  return [...by.entries()]
    .map(([id, uses]) => ({ id, label: (KIT[id] || {}).label || id, group: (KIT[id] || {}).group || "small", uses }))
    .sort((a, b) => order.indexOf(a.group) - order.indexOf(b.group) || b.uses.length - a.uses.length || a.label.localeCompare(b.label));
}

/* One line for a card: "Cable machine, rope attachment" or "Bodyweight". */
export function kitLine(name) {
  const r = kitOf(name);
  if (!r) return "";
  const labels = (r.kit || []).map((id) => (KIT[id] || {}).label || id);
  const all = labels.concat(r.setup || []);
  return all.length ? all.join(", ") : "Bodyweight, nothing to fetch";
}
