#!/usr/bin/env python3
"""Builds the Unio announcement film.

    python3 scripts/make-brand-film.py

Renders the app's own figure through scripts/render-bot-film.mjs, composites him
onto white with the copy, closes on the logo assembling itself, and encodes an
mp4. Nothing here is generated by a model: the character is our rig and the logo
is our artwork, so every frame is exactly the thing that ships.

The outro is the app's real boot animation, slowed down. The mark is a blue arc
and a coral arc closing into one ring around a dumbbell, which is the product's
whole argument stated in a shape, so the film ends by making that shape rather
than by fading up a finished logo.
"""
import json
import math
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "brand/film/figure"
COMP = ROOT / "brand/film/comp"
OUT = ROOT / "brand/film/unio-announce.mp4"

W, H = 1080, 1920            # 9:16
FPS = 30
SECONDS = 10.0
N = int(SECONDS * FPS)

WHITE = (255, 255, 255, 255)
INK = (17, 19, 24, 255)
MUTED = (110, 116, 128, 255)

# Two people either side of him. Mo: "bring in the guy and the woman, the same
# exact thing we had before." The rig has one character design and one face, so
# a coach plus two trainees would be three identical figures; instead the pair
# on screen IS the couple and UNIO is the voice in the bubble AND the only face
# in the shot. "none" (no face at all) is what makes them read as people rather
# than as two more robots.
#
# Position and scale are measured, not guessed: at chest height carrying the
# arms clear makes a figure wider, and the three of them side by side were
# overlapping at the old spacing.
CAST = [
    {"key": "man", "body": "film-man", "face": "none", "dx": -0.300,
     "t0": 1.00, "t1": 1.80, "how": "fade", "skin": "tan", "lines": True, "kit": True},
    {"key": "woman", "body": "film-woman", "face": "none", "dx": 0.300,
     "t0": 3.60, "t1": 4.20, "how": "pop", "skin": "tan", "lines": True, "kit": True},
    # Last in the list is drawn last, so he sits in FRONT of both of them and
    # her arm passes behind his rather than over it.
    {"key": "unio", "body": "male", "face": "none", "overlay": "buddy", "dx": 0.0,
     "t0": 0.00, "t1": 0.80, "how": "fade", "skin": None, "lines": False, "kit": False},
]
UNIO = 2

# UNIO Stand is Mountain Pose with the arms carried six degrees clear of the
# hips (built in brand/film-harness.html). Clothing is cut from each figure's
# own silhouette, and in Mountain Pose the arm and the hip are one unbroken run
# of pixels at that height: no threshold separates them, so a clothed forearm
# came out black. The clearance is not needed for UNIO, who wears no kit, but
# one move for the whole cast is simpler than two.
MOVE = "UNIO Stand"
MOVE_DUR = 6.4
# The blink is drawn here, not asked of the rig.
#
# The rig knows two eyes, open and closed, and switches between them on a 4.3
# second clock. Filmed, that is not a blink: it is the eyes teleporting shut for
# six frames and teleporting back, and it reads as a glitch because there is no
# frame in between. So the rig is held permanently open and the lids are drawn
# over the eyes here, which gives real in-between frames and exact control.
#
# Down fast, up slower, the way an eye actually moves, and the whole thing is
# over in a quarter of a second with almost none of it spent shut.
# Two, not four. Mo: "he's blinking too much, just a couple blinks in the
# beginning." One as he arrives and one as the wave comes down.
BLINKS = [(1.10, 0.09, 0.17), (4.15, 0.09, 0.17)]
# A last blink right before the cut, so the bloom that hides the swap comes out
# of a blink rather than arriving from nowhere.
BLINK_OUT = (6.20, 0.10, 0.20)
EYES_OPEN_AT = 1.0           # a face clock nowhere near the rig's own blink
# He keeps one face for the whole film. The rig's happy eyes are an upward arc
# and the neutral ones are vertical bars, and there is no shape in between, so
# switching read as a glitch however it was timed. Mo: "remove the upside down
# U, just keep him blinking the whole time."
MOOD = "neutral"
# Coming out of a blink the eyes flare, which is the moment Mo picked out of the
# Higgsfield pass and wanted in the source rather than bolted on afterwards.
GLOW_LEN = 0.55

FIG_UNTIL = 6.90             # the figures are on screen until here
# The push into his face, and the cut where it becomes the mark.
#
# This is the whole reason the mark went onto his face in the first place. Mo:
# "we have the dumbbell as the head, so now we can zoom in." His eyes ARE the
# artwork, at a smaller size, so the camera does not cut between two drawings
# that resemble each other: it pushes in on one drawing and stops pushing.
ZOOM_ON = UNIO
ZOOM_FROM, ZOOM_TO = 5.70, 6.90
ZOOM_MAX = 3.7
FIG_MOUTH = ROOT / "brand/film/figure-mouth"
# How much wider his face wears the mark than the bare pad-to-pad span, so it
# reads as features on a face rather than a sticker cut flush to its own edges.
FACE_MARK_PAD = 1.0
# Mo, after seeing hand-drawn eyes: "I think the transition will be much
# cleaner" with the actual mark on his face. He is right: a shape that merely
# resembles the mark is a dissolve between two different drawings; the mark
# itself is a zoom on one drawing.
EYE_NARROW = 0.86
EYE_RAISE = 0.22
# Full body, not a portrait. Measured, not guessed: at chest height with the
# arms held clear, the man is wider than UNIO, who is wider than the woman, and
# three of them at the old single-figure scale ran to 881px of a 1080 frame with
# no gap between them.
FIG_SCALE = 0.41             # of the frame height, head to feet
FIG_TOP = 0.15               # where the head starts, as a fraction of the frame

# He speaks, in the app's own bubble. Not a caption: the same white bubble with
# the notch on the corner nearest him, the same small COACH label, and the same
# green caret typing the line out a character at a time. Copying the app's own
# furniture is the cheapest way for a film to look like the product rather than
# like an advert for it.
# He has a name now. The app's bubble still says Coach; this is the film.
BOT_NAME = "UNIO"
# Mo: change the question, and add a second line once the wording lands.
# (text, arrives, last character lands, starts leaving)
SAYS = [
    ("Who will be joining us today?", 1.00, 2.60, 3.50),
    ("Let's begin.",                  3.85, 4.35, 5.30),
]
# No copy. Mo is adding his own, so the film is picture only and every second
# has to be carried by movement instead of by a sentence.
LINES = []

# The mark does not swing in any more, it draws itself on: both arcs start at
# the top and race round to meet at the bottom. That is the same gesture as the
# progress rings on the dashboard filling up, which makes the logo assemble the
# way the product works rather than the way a logo usually appears.
DRAW_FROM, DRAW_TO = 7.60, 8.70
# The mark arrives out of his eyes, so it is first and the arcs follow it.
BAR_FROM, BAR_TO = 6.85, 7.55
SWEEP_FROM, SWEEP_TO = 8.85, 9.65     # a specular band crossing the finished mark

# The end card. Set under the mark once it has finished assembling, in the app's
# own face, with the space above it left clear for anything Mo lays over the top.
END_NAME = "UNIO"
END_LINE = "Train together."
END_FROM = 8.90

SFPRO = "/System/Library/Fonts/SFNS.ttf"

# The two green pads on the dumbbell, measured off unio-bar.png by colour rather
# than guessed, in that file's own 853px space. They are tall vertical lime bars,
# which is the exact shape the rig draws his open eyes as, so the mark can blink
# with his face. Closing them is what turns a logo into the character.
# Found by colour when the film is built, not written down here. These were
# hardcoded against the old raster mark and silently pointed at empty plate the
# moment the artwork was redrawn.
PAD_BLEED = 8
BAR_PX = 853
# When the mark blinks, and which pads. (start, length, left, right)
MARK_BLINKS = [(8.80, 0.20, 1, 1), (9.45, 0.24, 0, 1)]
# The figure is rendered far larger than it is shown, because the shot is a
# portrait and the rig draws a whole standing body: at 1080 his head is about a
# hundred pixels tall, and cropping to it means upscaling the one part of the
# frame everything else is arranged around. Rendering at 2160 and cropping down
# keeps the eyes sharp, which is the entire reason for the shot.
RENDER = 2160


def ease_out(t):
    return 1 - (1 - t) ** 3


def smooth(t):
    """Ease in and out, symmetrically.

    The draw-on used ease_out, which is most of its travel in the first third
    and then a long crawl. On a stroke that is racing round a circle that does
    not read as easing, it reads as the animation giving up, so the sweep gets a
    curve that accelerates and decelerates by the same amount.
    """
    t = clamp01(t)
    return t * t * (3 - 2 * t)


def ease_out_back(t, k=1.70158):
    t -= 1
    return t * t * ((k + 1) * t + k) + 1


def pad_close(t):
    """How shut each green pad is at film time t, 0 open and 1 closed."""
    out = [0.0, 0.0]
    for at, span, l, r in MARK_BLINKS:
        if at <= t < at + span:
            # down and back up, so a blink is a movement rather than a cut
            k = (t - at) / span
            shut = math.sin(math.pi * k) ** 0.65
            out[0] = max(out[0], shut * l)
            out[1] = max(out[1], shut * r)
    return out


# Where the mark's arcs start and finish, clockwise from twelve o'clock, and the
# 2.4 degrees of clear air either side of the join. Has to agree with
# scripts/make-logo.py, which is where the artwork is drawn.
ARC_GAP = 2.4
# The stroke has round caps, and a cap bulges half a stroke-width PAST the end of
# the path it sits on. A wedge mask cut at exactly the end angle therefore slices
# through the middle of that cap and leaves a square end, which snaps to round
# the instant the reveal completes. Mo saw it: "it stops here and then it
# glitches and connects." Padding the wedge by the cap's own angular size at both
# ends means the caps are never cut and there is nothing to snap to.
# asin((stroke/2) / R) in degrees, with a little margin.
ARC_CAP = math.degrees(math.asin((116.39 / 2) / 441.81)) + 1.2


def arc_reveal(layer, side, p):
    """One arc, drawn on from the top by fraction p.

    A pie wedge from the centre does the cutting, because the arc is a ring
    around that same centre. Two things it cannot do on its own, both of which
    were visible on screen:

    The leading end. A wedge only ever cuts a straight radial line, so the end
    that is growing is a chevron for the entire reveal and then snaps round the
    instant it finishes. The fix is to union a circle the width of the stroke
    onto the mask at the leading end, which uncovers a round end out of the
    artwork that is already there.

    The edge quality. PIL fills shapes without antialiasing, so the cut is a
    stair and it crawls frame to frame. The mask is built at SS times size and
    scaled down, which is the cheapest antialiasing there is.
    """
    if p >= 0.999:
        return layer
    if p <= 0.001:
        return None
    w, h = layer.size
    SS = 4
    W2, H2 = w * SS, h * SS
    mask = Image.new("L", (W2, H2), 0)
    d = ImageDraw.Draw(mask)
    span = 180 - 2 * ARC_GAP
    # PIL measures from three o'clock; the artwork is measured from twelve.
    if side == "left":
        edge = (270 - ARC_GAP) - span * p
        d.pieslice([-W2, -H2, W2 * 2, H2 * 2], edge - ARC_CAP, 270 - ARC_GAP + ARC_CAP, fill=255)
    else:
        edge = (-90 + ARC_GAP) + span * p
        d.pieslice([-W2, -H2, W2 * 2, H2 * 2], -90 + ARC_GAP - ARC_CAP, edge + ARC_CAP, fill=255)

    # The round end, placed on the ring's centreline at the angle just reached.
    k = W2 / 1024.0
    r_ring, r_cap = 441.81 * k, (116.39 / 2) * k
    cx, cy = W2 / 2, H2 / 2
    ex = cx + r_ring * math.cos(math.radians(edge))
    ey = cy + r_ring * math.sin(math.radians(edge))
    d.ellipse([ex - r_cap, ey - r_cap, ex + r_cap, ey + r_cap], fill=255)

    mask = mask.resize((w, h), Image.LANCZOS)
    out = layer.copy()
    out.putalpha(ImageChops.multiply(out.getchannel("A"), mask))
    return out


def light_sweep(size, p, width=0.26):
    """A diagonal specular band crossing the mark once."""
    w, h = size
    band = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(band)
    # Travels from beyond the top-left corner to beyond the bottom-right.
    span = w * 2.4
    x = -w * 0.7 + span * p
    bw = w * width
    for i in range(int(bw)):
        k = i / bw
        v = int(255 * (1 - abs(k - 0.5) * 2) ** 1.6)
        d.line([(x + i, -h), (x + i - h * 1.6, h * 2)], fill=v)
    return band.filter(ImageFilter.GaussianBlur(w * 0.02))


# The app's bubble, measured off its CSS and scaled up for the frame. Values in
# index.html: white fill, a 10% ink hairline, radius 5px on the corner nearest
# him and 16px elsewhere, a soft low shadow, a 10px uppercase COACH label at
# .11em tracking in #8b94a3, the line at 14px/600 in #111318, and a 2px green
# caret. The film is 2.77x the app's 390px width, so everything here is that.
# The app draws this at 390px wide, and reproducing it at exactly that scale is
# technically faithful and practically useless: in a video it is a stamp under a
# full-height figure. Everything in the bubble is enlarged by BUB_SCALE so it
# reads at arm's length on a phone.
BUB_SCALE = 1.75
K = (1080 / 390) * BUB_SCALE
BUB_FILL = (255, 255, 255, 255)
BUB_EDGE = (17, 19, 24, 26)
BUB_LABEL = (139, 148, 163, 255)
BUB_INK = (17, 19, 24, 255)
BUB_CARET = (26, 163, 74, 255)


def bubble(text, shown, caret_on, fonts):
    """The bubble at its natural size, with `shown` characters typed."""
    f_who, f_line = fonts
    pad_x, pad_y = int(13 * K), int(10 * K)
    probe = ImageDraw.Draw(Image.new("RGBA", (8, 8)))
    tw = max(probe.textlength(text, font=f_line), probe.textlength(BOT_NAME, font=f_who))
    caret_w = int(2 * K)
    w = int(tw) + pad_x * 2 + caret_w + int(3 * K)
    line_h = int(f_line.size * 1.34)
    who_h = int(f_who.size * 1.5)
    h = pad_y * 2 + who_h + line_h

    im = Image.new("RGBA", (w + int(20 * K), h + int(20 * K)), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    box = [int(4 * K), int(2 * K), int(4 * K) + w, int(2 * K) + h]
    # The notch is the top-left corner, because the bubble hangs below him and a
    # tail pointing down would read as the floor talking.
    d.rounded_rectangle(box, radius=int(16 * K), fill=BUB_FILL, outline=BUB_EDGE, width=max(1, int(K)))
    d.rounded_rectangle([box[0], box[1], box[0] + int(30 * K), box[1] + int(30 * K)],
                        radius=int(5 * K), fill=BUB_FILL)

    tx, ty = box[0] + pad_x, box[1] + pad_y
    # Tracked out by hand: Pillow has no letter-spacing.
    lx = tx
    for ch in BOT_NAME:
        d.text((lx, ty), ch, font=f_who, fill=BUB_LABEL)
        lx += probe.textlength(ch, font=f_who) + 1.1 * K * 1.0
    ly = ty + who_h
    said = text[:shown]
    d.text((tx, ly), said, font=f_line, fill=BUB_INK)
    if caret_on:
        cx = tx + probe.textlength(said, font=f_line) + int(2 * K)
        d.rectangle([cx, ly + int(2 * K), cx + caret_w, ly + int(f_line.size * 1.0)], fill=BUB_CARET)
    return im


def neutral_floor(im, y0, body):
    """The rig's ground shadow is drawn in the accent lime.

    Under the figure in the app that is a deliberate tint. Scaled into a 9:16
    frame it becomes a hard green line running edge to edge under his feet,
    which reads as a stray stroke rather than as a shadow, so it is recoloured
    to a neutral. Only the strip below his knees is touched, which keeps his
    eyes, the other lime thing on screen, out of it.
    """
    top = int(y0 + body * 0.86)
    box = (0, top, im.width, im.height)
    strip = im.crop(box)
    r, g, b, a = strip.split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(hot(ImageChops.subtract(g, r), 25), hot(ImageChops.subtract(g, b), 25))
    grey = Image.new("RGBA", strip.size, (74, 80, 88, 0))
    grey.putalpha(a)
    lit = Image.composite(grey, strip, mask)

    # The rig's shadow is nearly as wide as its whole canvas. With one figure a
    # gentle fade is enough; with three side by side, each shadow reaches past
    # the other two and they join into one hard rule across the frame. Each now
    # falls off steeply into its own pool under its own feet.
    w = strip.width
    ramp_px = w * 0.42
    fall = Image.new("L", (w, 1), 0)
    fp = fall.load()
    for x in range(w):
        e = min(x, w - 1 - x)
        fp[x, 0] = 255 if e > ramp_px else int(255 * (e / ramp_px) ** 2.6)
    fall = fall.resize(strip.size)
    # Only the shadow fades; his feet keep their own alpha.
    faded = ImageChops.multiply(lit.getchannel("A"), fall)
    lit.putalpha(Image.composite(faded, lit.getchannel("A"), mask))

    out = im.copy()
    out.paste(lit, box)
    return out


# Black kit, cut out of each figure's own silhouette. The rig has no clothing
# layer at all: it draws one bare mannequin. But the alpha channel IS the body,
# so a vest and shorts can be taken from it directly, which means they fit the
# pose exactly and move with it rather than being a shape pasted over the top.
KIT = (24, 26, 30, 255)
VEST = (0.165, 0.430)        # as fractions of the figure's height
SHORTS = (0.425, 0.605)
KIT_REACH = 0.105            # how far from the centre line a run may sit, of figure width
KIT_SS = 4                   # the run-finding pass runs at 1/4 size; see clothe()


def clothe(im, y0, body, x0, x1):
    """Finding the runs a pixel at a time over a full-size row, for two
    figures, on hundreds of frames, is millions of reads and was the whole
    reason an early build of this took eighteen minutes. Run finding happens on
    a quarter-size copy here, and the resulting shape is intersected with the
    FULL size alpha afterward, so the garment's edges are the figure's own and
    nothing is softened by the detour.
    """
    W_, H_ = im.size
    sw, sh = W_ // KIT_SS, H_ // KIT_SS
    small = im.getchannel("A").resize((sw, sh), Image.BILINEAR)
    px = small.load()
    cx = (x0 + x1) / 2 / KIT_SS
    reach = (x1 - x0) * KIT_REACH / KIT_SS
    rough = Image.new("L", (sw, sh), 0)
    d = ImageDraw.Draw(rough)
    for lo, hi in (VEST, SHORTS):
        for y in range(max(0, int((y0 + body * lo) / KIT_SS)), min(sh, int((y0 + body * hi) / KIT_SS))):
            run = None
            for x in range(sw):
                on = px[x, y] > 150
                if on and run is None:
                    run = x
                elif not on and run is not None:
                    if abs((run + x - 1) / 2 - cx) < reach:
                        d.line([(run, y), (x - 1, y)], fill=255)
                    run = None
            if run is not None and abs((run + sw - 1) / 2 - cx) < reach:
                d.line([(run, y), (sw - 1, y)], fill=255)
    mask = ImageChops.multiply(rough.resize((W_, H_), Image.BILINEAR).point(lambda v: 255 if v > 140 else 0),
                               im.getchannel("A").point(lambda v: 255 if v > 150 else 0))
    kit = Image.new("RGBA", (W_, H_), KIT)
    kit.putalpha(mask)
    out = im.copy()
    out.alpha_composite(kit)
    return out


def soft_shadow(im, blur, dy, opacity):
    """The bubble's own drop shadow, from its alpha."""
    w, h = im.size
    sh = Image.new("RGBA", (w, h + dy), (0, 0, 0, 0))
    a = im.getchannel("A").point(lambda v: int(v * opacity))
    tint = Image.new("RGBA", (w, h), (11, 13, 17, 0))
    tint.putalpha(a)
    sh.alpha_composite(tint, (0, dy))
    return sh.filter(ImageFilter.GaussianBlur(blur))


def pad_boxes(bar):
    """The two lime pads on the dumbbell, located by colour."""
    r, g, b, a = bar.split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(
        ImageChops.multiply(hot(ImageChops.subtract(g, r), 60), hot(ImageChops.subtract(g, b), 60)),
        hot(a, 60))
    bb = mask.getbbox()
    if not bb:
        return []
    x0, y0, x1, y1 = bb
    mid = (x0 + x1) // 2
    out = []
    for lo, hi in ((x0, mid), (mid, x1)):
        sub = mask.crop((lo, y0, hi, y1)).getbbox()
        if not sub:
            return []
        out.append((lo + sub[0], y0 + sub[1], lo + sub[2], y0 + sub[3]))
    return out


def blink_bar(base, closes, boxes):
    """The dumbbell with its pads part shut.

    The lids are drawn in the plate's own colour sampled row by row from just
    beside each pad, rather than a flat fill, because the plate is shaded top to
    bottom and a flat grey rectangle sitting on it reads as a bug.
    """
    if (closes[0] < 0.01 and closes[1] < 0.01) or not boxes:
        return base
    im = base.copy()
    px = im.load()
    d = ImageDraw.Draw(im)
    for (x0, y0, x1, y1), c in zip(boxes, closes):
        if c < 0.01:
            continue
        drop = (y1 - y0) * 0.5 * c
        for y in range(y0 - PAD_BLEED, y1 + PAD_BLEED + 1):
            if not (y < y0 + drop or y > y1 - drop):
                continue
            yy = min(max(y, 0), im.height - 1)
            d.line([(x0 - PAD_BLEED, yy), (x1 + PAD_BLEED, yy)],
                   fill=px[max(0, x0 - 22), yy])
    return im


def cam(t):
    """The camera: how far zoomed in, and how far the centre has travelled.

    One formula for the whole film, deliberately. An earlier version used plain
    placement below a threshold and a camera transform above it, and the two do
    not agree: the transform centres on his EYES, which are nowhere near the
    middle of the frame, so on the first frame of the push everything jumped by
    the distance between the two. The centre travels from mid-frame to his eyes
    on the same eased curve as the zoom, so at rest this IS the plain wide shot
    and there is nothing to switch between.
    """
    k = 0.0 if t <= ZOOM_FROM else smooth((t - ZOOM_FROM) / (ZOOM_TO - ZOOM_FROM))
    return 1.0 + (ZOOM_MAX - 1.0) * k, k


def clamp01(x):
    return 0.0 if x < 0 else 1.0 if x > 1 else x


def ramp(t, a, b):
    """0 before a, 1 after b, eased between."""
    if b <= a:
        return 1.0 if t >= b else 0.0
    return ease_out(clamp01((t - a) / (b - a)))


def eye_close(t):
    """How shut his eyes are at film time t, 0 open and 1 closed."""
    for at, dn, up in BLINKS + [BLINK_OUT]:
        if at <= t < at + dn:
            return ease_out((t - at) / dn)
        if at + dn <= t < at + dn + up:
            return 1 - ease_out((t - at - dn) / up)
    return 0.0


def eye_flare(t):
    """How lit his eyes are, 0 to 1. Rises as the lids open and decays after."""
    out = 0.0
    # The last one does not decay: it keeps climbing into the cut, so the bloom
    # is at its brightest exactly where his eyes become the mark.
    #
    # clamp01 BEFORE the exponent. The guard is `a + dn <= t`, but this computes
    # (t - a) - dn, and the two associate differently in floating point: on the
    # exact frame where they meet the result is about -9e-16, and a negative
    # base with a fractional exponent is a complex number in Python. That blew
    # up a render 183 frames in.
    a, dn, up = BLINK_OUT
    if a + dn <= t <= ZOOM_TO:
        out = max(out, clamp01((t - a - dn) / max(0.01, ZOOM_TO - a - dn)) ** 0.8)
    for at, dn, up in BLINKS:
        start = at + dn
        if start <= t < start + GLOW_LEN:
            k = (t - start) / GLOW_LEN
            # up fast with the lids, then a slow falloff
            out = max(out, (min(1.0, k / 0.28) if k < 0.28 else (1 - (k - 0.28) / 0.72) ** 1.5))
    return out


def glow_eyes(im, boxes, amount):
    """A lime bloom over the eyes, drawn from their own shape and blurred."""
    if amount < 0.02 or not boxes:
        return im
    w, h = im.size
    lay = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(lay)
    for x0, y0, x1, y1 in boxes:
        pad = (y1 - y0) * 0.16
        d.rounded_rectangle([x0 - pad, y0 - pad, x1 + pad, y1 + pad],
                            radius=(x1 - x0) / 2 + pad, fill=255)
    lay = lay.filter(ImageFilter.GaussianBlur((boxes[0][3] - boxes[0][1]) * 0.42))
    glow = Image.new("RGBA", (w, h), (168, 255, 0, 0))
    glow.putalpha(lay.point(lambda v: int(v * 0.85 * amount)))
    out = im.copy()
    out.alpha_composite(glow)
    return out


def eye_boxes(im):
    """The two eyes in a rendered figure frame, found by colour.

    Only the head is searched. The same lime turns up on the floor line under
    him, and a bounding box taken over the whole frame quietly stretches from
    his eyes to his feet.
    """
    fx0, fy0, fx1, fy1 = im.getbbox()
    head = (fx0, fy0, fx1, fy0 + int((fy1 - fy0) * 0.20))
    r, g, b, a = im.crop(head).split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(
        ImageChops.multiply(hot(ImageChops.subtract(g, r), 40), hot(ImageChops.subtract(g, b), 40)),
        hot(a, 60))
    bb = mask.getbbox()
    if not bb:
        return None
    # He has a lime mouth as well as lime eyes, so the bounding box of all the
    # green on his face runs from his eyebrows to his chin, and a lid drawn over
    # that is a dark rectangle across the whole head. Take the topmost run of
    # green rows and nothing below it.
    hh = mask.size[1]
    rows = list(mask.resize((1, hh), Image.BOX).getdata())
    top = next((y for y in range(hh) if rows[y] > 0), None)
    if top is None:
        return None
    end = next((y for y in range(top, hh) if rows[y] == 0), hh)
    mask = mask.crop((0, top, mask.size[0], end))
    bb = mask.getbbox()
    if not bb:
        return None
    x0, y0, x1, y1 = bb
    y0 += top
    y1 += top
    mid = (x0 + x1) // 2
    out = []
    for lo, hi in ((x0, mid), (mid, x1)):
        sub = mask.crop((lo, y0 - top, hi, y1 - top)).getbbox()
        if not sub:
            return None
        out.append((head[0] + lo + sub[0], head[1] + y0 + sub[1],
                    head[0] + lo + sub[2], head[1] + y0 + sub[3]))
    return out


def blink_eyes(im, close, boxes):
    """Lids drawn over his eyes, in the visor's own colour."""
    if close < 0.01 or not boxes:
        return im
    out = im.copy()
    px = out.load()
    d = ImageDraw.Draw(out)
    # Between the eyes is clean visor. Outside them are the little dark ticks,
    # so sampling there would paint the lid the wrong grey.
    visor = px[(boxes[0][2] + boxes[1][0]) // 2, (boxes[0][1] + boxes[0][3]) // 2]
    # Just enough to swallow the eye's antialiased edge and its glow. Any more
    # and the lid paints over the visor's own outline, and the whole dark band
    # visibly grows as he blinks.
    bleed = max(2, round((boxes[0][3] - boxes[0][1]) * 0.05))
    for x0, y0, x1, y1 in boxes:
        drop = (y1 - y0) * 0.5 * close
        d.rectangle([x0 - bleed, y0 - bleed, x1 + bleed, y0 + drop], fill=visor)
        d.rectangle([x0 - bleed, y1 - drop, x1 + bleed, y1 + bleed], fill=visor)
    return out


def unio_face(base, bud, close, bar_src, bar_pads):
    """His face: a bare head, the mark itself where the eyes go, and the
    mouth lifted off a second, ordinary render of him.

    Position and scale are measured off the ordinary (buddy-faced) pass, so the
    mark rides his head as it sways with his breathing rather than sitting
    still while he moves underneath it. Blinking reuses blink_bar(), the exact
    function the end-card mark uses on itself, so his face and the logo close
    their eyes the same way because it is the same code doing it.
    """
    bb = bud.getbbox()
    if not bb or bar_src is None or not bar_pads:
        return base
    h = bb[3] - bb[1]
    r, g, b, a = bud.split()
    hot = lambda ch, t, inv=False: ch.point(lambda v: (255 if v < t else 0) if inv else (255 if v > t else 0))
    dark = ImageChops.multiply(ImageChops.multiply(hot(r, 70, True), hot(g, 80, True)),
                               ImageChops.multiply(hot(b, 95, True), hot(a, 150)))
    lime = ImageChops.multiply(ImageChops.multiply(hot(ImageChops.subtract(g, r), 40),
                                                   hot(ImageChops.subtract(g, b), 40)), hot(a, 60))
    # The visor is the widest dark band on the head. Scanning the whole figure
    # finds his shoulders instead, so this stops at the jaw.
    rows = [(y, sum(1 for v in dark.crop((bb[0], y, bb[2], y + 1)).getdata() if v > 128))
            for y in range(bb[1], bb[1] + int(h * 0.13))]
    widest = max(c for _, c in rows) or 1
    band = [y for y, c in rows if c > widest * 0.6]
    if not band:
        return base
    vb = band[-1]

    lr = [sum(1 for v in lime.crop((bb[0], y, bb[2], y + 1)).getdata() if v > 128) for y in range(bb[1], vb + 1)]
    if not any(lr):
        return base
    top = next(i for i, v in enumerate(lr) if v > 0)
    end = next((i for i in range(top, len(lr)) if lr[i] == 0), len(lr))
    ey0, ey1 = bb[1] + top, bb[1] + end
    ex = lime.crop((bb[0], ey0, bb[2], ey1)).getbbox()
    if not ex:
        return base
    x0, x1 = bb[0] + ex[0], bb[0] + ex[2]
    ecx, ecy = (x0 + x1) / 2, (ey0 + ey1) / 2
    eh = ey1 - ey0

    # Scale the real mark so ITS pad pair spans the width his drawn eyes used
    # to occupy. Both spans are outer edge to outer edge.
    bar_span = bar_pads[1][2] - bar_pads[0][0]
    # x1-x0 is already the full outer-edge-to-outer-edge span of the eye pair,
    # directly comparable to bar_span (left pad's outer edge to right pad's).
    # An earlier version multiplied this by 2 on top of that, which is why his
    # first render wore the mark like a pair of headphones twice the width of
    # his head.
    target_span = (x1 - x0) * FACE_MARK_PAD
    scale = target_span / bar_span
    mw, mh = max(1, int(bar_src.width * scale)), max(1, int(bar_src.height * scale))

    lit = blink_bar(bar_src, [close, close], bar_pads)
    mk = lit.resize((mw, mh), Image.LANCZOS)
    # Vertical placement keys off where the PADS land in the resized mark, not
    # its bounding box, so the eyes sit at eye height however much plate frames
    # them above and below.
    pad_cy = (bar_pads[0][1] + bar_pads[0][3]) / 2 * scale
    mx = int(ecx - mw / 2)
    my = int(ecy - eh * EYE_RAISE - pad_cy)

    out = base.copy()
    out.alpha_composite(mk, (mx, my))
    # The mouth and the chin light, taken as their own pixels rather than as a
    # rectangle, so nothing of the visor above them comes with it.
    cut = Image.new("L", bud.size, 0)
    ImageDraw.Draw(cut).rectangle([0, vb + 6, bud.width, bb[1] + int(h * 0.135)], fill=255)
    mouth = bud.copy()
    mouth.putalpha(ImageChops.multiply(bud.getchannel("A"),
                                       ImageChops.multiply(ImageChops.lighter(dark, lime), cut)))
    out.alpha_composite(mouth)
    return out


def shot_list():
    shots = []
    for f in range(int(FIG_UNTIL * FPS)):
        t = f / FPS
        shots.append({
            # A standing hold, so the cycle is just the pose breathing.
            "cycle": round((0.10 + t / MOVE_DUR) % 1, 6),
            "face": EYES_OPEN_AT,
            "mood": MOOD,
        })
    return shots


def render_figure(shots):
    """One pass per cast member, plus a second pass for whoever has an
    "overlay" face (UNIO: a bare head to build his face on, and an ordinary
    render of him to lift the mouth off).
    """
    tmp = Path("/tmp/unio-shots.json")
    tmp.write_text(json.dumps(shots))
    jobs = []
    for c in CAST:
        jobs.append((c["key"], c["body"], c["face"], c["lines"], c["skin"]))
        if c.get("overlay"):
            jobs.append((c["key"] + "-face", c["body"], c["overlay"], c["lines"], c["skin"]))
    for key, body, face, lines, skin in jobs:
        out = FIG / key
        if out.exists() and len(list(out.glob("f*.png"))) >= len(shots):
            continue
        print(f"rendering {len(shots)} frames for {key}")
        cmd = [
            "node", str(ROOT / "scripts/render-bot-film.mjs"),
            "--shots", str(tmp), "--out", str(out), "--size", str(RENDER),
            "--move", MOVE, "--theme", "light",
            "--face", face, "--body", body, "--lines", "true" if lines else "false",
        ]
        if skin:
            cmd += ["--skin", skin]
        subprocess.run(cmd, check=True)


def font(size, weight="Regular"):
    try:
        f = ImageFont.truetype(SFPRO, size)
        try:
            f.set_variation_by_name(weight)
        except Exception:
            pass
        return f
    except Exception:
        return ImageFont.load_default()


def centred(d, y, text, f, fill, alpha=1.0, track=0):
    if alpha <= 0.01:
        return
    w = d.textlength(text, font=f) + track * (len(text) - 1)
    x = (W - w) / 2
    col = (fill[0], fill[1], fill[2], int(255 * alpha))
    if track:
        for ch in text:
            d.text((x, y), ch, font=f, fill=col)
            x += d.textlength(ch, font=f) + track
    else:
        d.text((x, y), text, font=f, fill=col)


def fade(im, a):
    if a >= 0.999:
        return im
    out = im.copy()
    alpha = out.getchannel("A").point(lambda v: int(v * a))
    out.putalpha(alpha)
    return out


def main():
    shots = shot_list()
    render_figure(shots)
    cast_frames = {c["key"]: sorted((FIG / c["key"]).glob("f*.png")) for c in CAST}
    faces = {c["key"]: sorted((FIG / (c["key"] + "-face")).glob("f*.png"))
             for c in CAST if c.get("overlay")}
    figs = cast_frames[CAST[0]["key"]]
    if not figs or any(len(v) < len(figs) for v in cast_frames.values()):
        sys.exit("no figure frames")

    # One shared scale, taken off UNIO's own height rather than any of theirs,
    # since he is the reference character regardless of which two people stand
    # beside him. Each cast member's own width then follows from their own body
    # proportions at that same scale, which is why the three of them come out
    # different widths despite standing at the same "distance".
    ref = Image.open(cast_frames[CAST[UNIO]["key"]][0]).convert("RGBA")
    rx0, ry0, rx1, ry1 = ref.getbbox()
    fscale = (H * FIG_SCALE) / (ry1 - ry0)

    # Per cast member: their own bbox, in their own frame's coordinates, and
    # where their scaled canvas has to sit for their head to land on FIG_TOP.
    layout = {}
    for c in CAST:
        p0 = Image.open(cast_frames[c["key"]][0]).convert("RGBA")
        bx0, by0, bx1, by1 = p0.getbbox()
        fw_c, fh_c = int(p0.width * fscale), int(p0.height * fscale)
        layout[c["key"]] = {
            "x0": bx0, "y0": by0, "x1": bx1, "body": by1 - by0,
            "fw": fw_c, "fh": fh_c,
            "left": (W - fw_c) // 2 + int(c["dx"] * W),
            "top": int(H * FIG_TOP) - int(by0 * fscale),
        }

    # His eyes, measured once in his own canvas coordinates. They only exist
    # once the face has been assembled, so the probe has to be assembled too or
    # there is nothing to aim at. Measured once rather than per frame so the
    # camera is steady: he sways inside a still camera, which is what a real one
    # does, instead of the camera chasing his breathing.
    u_key = CAST[ZOOM_ON]["key"]
    eprobe = Image.open(cast_frames[u_key][0]).convert("RGBA")
    _bar_probe = Image.open(ROOT / "brand/unio-bar.png").convert("RGBA")
    eprobe = unio_face(eprobe, Image.open(faces[u_key][0]).convert("RGBA"),
                       0.0, _bar_probe, pad_boxes(_bar_probe))
    ebox = eye_boxes(eprobe)
    if not ebox:
        sys.exit("could not find the eyes to push in on")
    eye_cx_c = (ebox[0][0] + ebox[1][2]) / 2
    eye_cy_c = (ebox[0][1] + ebox[0][3]) / 2
    eye_h_c = ebox[0][3] - ebox[0][1]

    arcL = Image.open(ROOT / "brand/unio-left.png").convert("RGBA")
    arcR = Image.open(ROOT / "brand/unio-right.png").convert("RGBA")
    # The bar stays at its native size until the last moment: the lids are drawn
    # at the resolution the pads were measured at, then the whole thing is scaled
    # once, so the closed edges get the same antialiasing as the artwork.
    bar_src = Image.open(ROOT / "brand/unio-bar.png").convert("RGBA")
    bar_pads = pad_boxes(bar_src)
    mark = 730
    # What the mark has to measure for its pads to be exactly as tall as his
    # eyes were on the last frame before the cut. Both are centred, so matching
    # the height puts them in the same place, and since his eyes are drawn FROM
    # this artwork it is the same picture at the same size: nothing swaps.
    _sc_cut = (1.030 - 0.030) * (1.0 + 0.030 * clamp01(ZOOM_TO / FIG_UNTIL))
    pad_h_native = (pad_boxes(_bar_probe)[0][3] - pad_boxes(_bar_probe)[0][1]) or 155
    mark_at_cut = (eye_h_c * fscale * _sc_cut * ZOOM_MAX) * _bar_probe.height / pad_h_native
    print(f"  his eyes are {eye_h_c * fscale * _sc_cut * ZOOM_MAX:.0f}px tall at the cut, "
          f"so the mark arrives at {mark_at_cut:.0f}px and settles to {mark}px")
    arcL = arcL.resize((mark, mark), Image.LANCZOS)
    arcR = arcR.resize((mark, mark), Image.LANCZOS)
    mx, my = (W - mark) // 2, (H - mark) // 2

    f_name = font(104, "Bold")
    f_end = font(50, "Medium")
    f_who = font(int(10 * K), "Heavy")
    f_line = font(int(14 * K), "Semibold")
    bub_y = int(H * 0.795)
    # Measured at full length and shrunk to fit, rather than trusting a scale
    # factor to be right: at 1.75 this line came out 1216px wide in a 1080 frame
    # and was clipped at both ends. Now any line Mo writes fits or is made to.
    BUB_MAX = W - 2 * 46
    natural = max(bubble(t, len(t), False, (f_who, f_line)).width for t, *_ in SAYS)
    bub_fit = min(1.0, BUB_MAX / natural)

    COMP.mkdir(parents=True, exist_ok=True)
    for old in COMP.glob("*.png"):
        old.unlink()

    for i in range(N):
        t = i / FPS
        frame = Image.new("RGBA", (W, H), WHITE)

        # ---- the three of them ----
        # He holds full strength right up to the cut; the bloom does the hiding,
        # not a fade.
        a_out = 1 - ramp(t, FIG_UNTIL - 0.07, FIG_UNTIL)
        if a_out > 0.01 and i < len(figs):
            # Everyone drifts very slightly closer for the whole shot. The move
            # is small enough that nobody sees it happening and the frame still
            # refuses to sit dead still, which is the difference between calm
            # and inert.
            settle = 1.030 - 0.030 * ease_out(clamp01(t / 0.70))
            push = 1.0 + 0.030 * clamp01(t / FIG_UNTIL)
            sc = settle * push
            z, ck = cam(t)
            # Where his eyes actually are this frame, at this scale, so the push
            # lands on them and not three per cent to one side of them.
            u_lay = layout[u_key]
            eye_wx = u_lay["left"] - (u_lay["fw"] * sc - u_lay["fw"]) / 2 + eye_cx_c * fscale * sc
            eye_wy = u_lay["top"] - (u_lay["fh"] * sc - u_lay["fh"]) / 2 + eye_cy_c * fscale * sc
            ccx = W / 2 + (eye_wx - W / 2) * ck
            ccy = H / 2 + (eye_wy - H / 2) * ck
            for c in CAST:
                lay = layout[c["key"]]
                # Each of them arrives on their own beat. UNIO fades up alone
                # first so the frame is his; the man fades in while the
                # question is still forming; she pops in after it is asked,
                # which makes her the answer to it rather than scenery.
                p = clamp01((t - c["t0"]) / max(0.01, c["t1"] - c["t0"]))
                if p <= 0.001:
                    continue
                if c["how"] == "pop":
                    ea, es, rise = p, 0.88 + 0.12 * ease_out_back(p), int(70 * (1 - ease_out(p)))
                else:
                    ea, es, rise = ease_out(p), 1.0, 0
                a = a_out * ea
                if a <= 0.01:
                    continue
                fw_c, fh_c = lay["fw"], lay["fh"]
                w2, h2 = int(fw_c * sc * es), int(fh_c * sc * es)
                w3, h3 = int(w2 * z), int(h2 * z)
                if w3 < 4 or h3 < 4 or w3 > 26000 or h3 > 26000:
                    continue
                src = Image.open(cast_frames[c["key"]][i]).convert("RGBA")
                k = w3 / src.width
                im = src.resize((w3, h3), Image.LANCZOS)
                im = neutral_floor(im, lay["y0"] * k, lay["body"] * k)
                if c["kit"]:
                    im = clothe(im, lay["y0"] * k, lay["body"] * k, lay["x0"] * k, lay["x1"] * k)
                if c.get("overlay"):
                    ov = Image.open(faces[c["key"]][i]).convert("RGBA").resize((w3, h3), Image.LANCZOS)
                    im = unio_face(im, ov, eye_close(t), bar_src, bar_pads)
                    boxes = eye_boxes(im)
                    im = glow_eyes(im, boxes, eye_flare(t))
                # Where they stand in the wide shot, then the camera applied.
                # Everything scales about the point being pushed in on, so
                # nobody walks across the frame as it moves.
                wx = lay["left"] - (w2 - fw_c) / 2
                wy = lay["top"] - (h2 - fh_c) / 2 + rise
                sx = (wx - ccx) * z + W / 2
                sy = (wy - ccy) * z + H / 2
                # Drawn in CAST order, so UNIO, listed last, paints over both of
                # them: her arm passes behind his rather than over it.
                frame.alpha_composite(fade(im, a), (int(sx), int(sy)))

        # ---- he speaks ----
        for text, s_from, s_typed, s_until in SAYS:
            if not (s_from <= t < s_until + 0.45):
                continue
            grow = ease_out(clamp01((t - s_from) / 0.30))
            gone = ramp(t, s_until, s_until + 0.45)
            ba = grow * (1 - gone)
            if ba > 0.01:
                typed = clamp01((t - s_from - 0.18) / max(0.01, s_typed - s_from - 0.18))
                shown = int(len(text) * typed)
                # The caret blinks while he types and goes the moment he stops,
                # which is exactly what typeQuip does in the app.
                caret = shown < len(text) and int(t * 2.2) % 2 == 0
                bub = bubble(text, shown, caret, (f_who, f_line))
                # It arrives from slightly below and small, like the app's quipIn.
                sc = (0.94 + 0.06 * grow) * bub_fit
                bw, bh = int(bub.width * sc), int(bub.height * sc)
                b = bub.resize((bw, bh), Image.LANCZOS)
                bx = (W - bw) // 2
                by = bub_y + int(14 * (1 - grow))
                frame.alpha_composite(fade(soft_shadow(b, 12, 10, 0.28), ba), (bx, by))
                frame.alpha_composite(fade(b, ba), (bx, by))
            break

        # ---- the mark assembling ----
        draw_p = smooth((t - DRAW_FROM) / (DRAW_TO - DRAW_FROM))
        # The mark arrives out of his eyes BEFORE the arcs start drawing, so
        # this cannot be gated on the arc reveal alone: that left half a second
        # of pure white between his last frame and the ring's first.
        if draw_p > 0.001 or t >= BAR_FROM:
            layer = Image.new("RGBA", (mark, mark), (0, 0, 0, 0))
            for img, side in ((arcL, "left"), (arcR, "right")):
                piece = arc_reveal(img, side, draw_p)
                if piece is not None:
                    layer.alpha_composite(piece)

            # The dumbbell does not drop in any more: it is already there, full
            # size, because it IS his eyes. What moves is the camera coming off
            # it.
            if t >= BAR_FROM:
                layer.alpha_composite(
                    blink_bar(bar_src, pad_close(t), bar_pads).resize((mark, mark), Image.LANCZOS))

            sp = clamp01((t - SWEEP_FROM) / (SWEEP_TO - SWEEP_FROM))
            if 0.001 < sp < 0.999:
                # Clipped to the mark's own alpha, so the light runs across the
                # artwork instead of across the white behind it.
                shine = Image.new("RGBA", (mark, mark), (255, 255, 255, 255))
                band = light_sweep((mark, mark), sp)
                shine.putalpha(ImageChops.multiply(
                    ImageChops.multiply(band, layer.getchannel("A")),
                    Image.new("L", (mark, mark), 120)))
                layer.alpha_composite(shine)

            # ---- the pull back ----
            # The mark starts at exactly the size his eyes just were and settles
            # to its own. That is the whole illusion: nothing dissolves, the
            # camera simply stops pushing and comes off it.
            pull = ease_out(clamp01((t - BAR_FROM) / (BAR_TO - BAR_FROM)))
            ms = int(mark_at_cut + (mark - mark_at_cut) * pull) if t >= BAR_FROM else mark
            ms = max(8, min(ms, 4200))
            shown = layer.resize((ms, ms), Image.LANCZOS)

            # The bloom off his eyes carries across the cut and decays on the
            # pads, so there is no frame where the swap is visible.
            bl = 1 - clamp01((t - BAR_FROM) / 0.42)
            if bl > 0.02 and bar_pads:
                kk = ms / bar_src.height
                lay_g = Image.new("L", (ms, ms), 0)
                dg = ImageDraw.Draw(lay_g)
                for px0, py0, px1, py1 in bar_pads:
                    pd = (py1 - py0) * 0.18
                    dg.rounded_rectangle([(px0 - pd) * kk, (py0 - pd) * kk,
                                          (px1 + pd) * kk, (py1 + pd) * kk],
                                         radius=((px1 - px0) / 2 + pd) * kk, fill=255)
                lay_g = lay_g.filter(ImageFilter.GaussianBlur(
                    max(2.0, (bar_pads[0][3] - bar_pads[0][1]) * 0.42 * kk)))
                glow = Image.new("RGBA", (ms, ms), (168, 255, 0, 0))
                glow.putalpha(lay_g.point(lambda v: int(v * 0.9 * bl)))
                shown.alpha_composite(glow)

            frame.alpha_composite(shown, ((W - ms) // 2, (H - ms) // 2))

            ea = ramp(t, END_FROM, END_FROM + 0.55)
            if ea > 0.01:
                d = ImageDraw.Draw(frame)
                rise = int(16 * (1 - ea))
                centred(d, my + mark + 86 + rise, END_NAME, f_name, INK, ea, track=12)
                # The tagline follows a beat later, so the name lands first.
                la = ramp(t, END_FROM + 0.30, END_FROM + 0.85)
                if la > 0.01:
                    centred(d, my + mark + 196 + int(14 * (1 - la)), END_LINE, f_end, MUTED, la)

        frame.convert("RGB").save(COMP / f"c{i:04d}.png")

    encode()


def encode():
    import imageio_ffmpeg
    exe = imageio_ffmpeg.get_ffmpeg_exe()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([
        exe, "-y", "-framerate", str(FPS), "-i", str(COMP / "c%04d.png"),
        "-c:v", "libx264", "-preset", "slow", "-crf", "17",
        # yuv420p and even dimensions, or half the places you post it will
        # refuse the file or show a green channel.
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        str(OUT),
    ], check=True, capture_output=True)
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB, {N} frames at {FPS}fps)")


if __name__ == "__main__":
    main()
