#!/usr/bin/env python3
"""Builds the Unio announcement film.

    python3 scripts/make-brand-film.py

Renders the app's own figure through scripts/render-bot-film.mjs, composites him
onto white with the copy, closes on the logo assembling itself, and encodes an
mp4. Nothing here is generated by a model: the character is our rig and the logo
is our artwork, so every frame is exactly the thing that ships.

The outro is the app's real boot animation, slowed down. The mark is a blue arc
and a coral arc closing into one ring around a dumbbell, which is the product's
whole argument stated in a shape, so the film ends by making that shape rather
than by fading up a finished logo.
"""
import json
import math
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "brand/film/figure"
COMP = ROOT / "brand/film/comp"
OUT = ROOT / "brand/film/unio-announce.mp4"

W, H = 1080, 1350
FPS = 30
SECONDS = 8.0
N = int(SECONDS * FPS)

WHITE = (255, 255, 255, 255)
INK = (17, 19, 24, 255)
MUTED = (110, 116, 128, 255)

MOVE = "Mountain Pose"
MOVE_DUR = 6.4
# The blink is drawn here, not asked of the rig.
#
# The rig knows two eyes, open and closed, and switches between them on a 4.3
# second clock. Filmed, that is not a blink: it is the eyes teleporting shut for
# six frames and teleporting back, and it reads as a glitch because there is no
# frame in between. So the rig is held permanently open and the lids are drawn
# over the eyes here, which gives real in-between frames and exact control.
#
# Down fast, up slower, the way an eye actually moves, and the whole thing is
# over in a quarter of a second with almost none of it spent shut.
BLINKS = [(1.40, 0.09, 0.17), (3.05, 0.09, 0.17), (4.45, 0.08, 0.15)]
EYES_OPEN_AT = 1.0           # a face clock nowhere near the rig's own blink
# He changes expression behind closed lids, which is how it is done by hand and
# why the mood switch does not read as a cut.
HAPPY_FROM = 3.14

FIG_UNTIL = 5.3              # the figure is on screen until here
# No copy. Mo is adding his own, so the film is picture only and every second
# has to be carried by movement instead of by a sentence.
LINES = []

# The mark does not swing in any more, it draws itself on: both arcs start at
# the top and race round to meet at the bottom. That is the same gesture as the
# progress rings on the dashboard filling up, which makes the logo assemble the
# way the product works rather than the way a logo usually appears.
DRAW_FROM, DRAW_TO = 5.10, 6.35
BAR_FROM, BAR_TO = 6.30, 6.78
SWEEP_FROM, SWEEP_TO = 7.05, 7.85     # a specular band crossing the finished mark

SFPRO = "/System/Library/Fonts/SFNS.ttf"

# The two green pads on the dumbbell, measured off unio-bar.png by colour rather
# than guessed, in that file's own 853px space. They are tall vertical lime bars,
# which is the exact shape the rig draws his open eyes as, so the mark can blink
# with his face. Closing them is what turns a logo into the character.
# Found by colour when the film is built, not written down here. These were
# hardcoded against the old raster mark and silently pointed at empty plate the
# moment the artwork was redrawn.
PAD_BLEED = 8
BAR_PX = 853
# When the mark blinks, and which pads. (start, length, left, right)
MARK_BLINKS = [(6.92, 0.20, 1, 1), (7.62, 0.26, 0, 1)]
# The figure is rendered far larger than it is shown, because the shot is a
# portrait and the rig draws a whole standing body: at 1080 his head is about a
# hundred pixels tall, and cropping to it means upscaling the one part of the
# frame everything else is arranged around. Rendering at 2160 and cropping down
# keeps the eyes sharp, which is the entire reason for the shot.
RENDER = 2160


def ease_out(t):
    return 1 - (1 - t) ** 3


def ease_out_back(t, k=1.70158):
    t -= 1
    return t * t * ((k + 1) * t + k) + 1


def pad_close(t):
    """How shut each green pad is at film time t, 0 open and 1 closed."""
    out = [0.0, 0.0]
    for at, span, l, r in MARK_BLINKS:
        if at <= t < at + span:
            # down and back up, so a blink is a movement rather than a cut
            k = (t - at) / span
            shut = math.sin(math.pi * k) ** 0.65
            out[0] = max(out[0], shut * l)
            out[1] = max(out[1], shut * r)
    return out


# Where the mark's arcs start and finish, clockwise from twelve o'clock, and the
# 2.4 degrees of clear air either side of the join. Has to agree with
# scripts/make-logo.py, which is where the artwork is drawn.
ARC_GAP = 2.4


def arc_reveal(layer, side, p):
    """One arc, drawn on from the top by fraction p.

    A wedge from the centre is used as a mask rather than anything cleverer: the
    arc is a ring around that centre, so a pie slice cuts it at exactly the angle
    wanted and the artwork's own antialiasing survives.
    """
    if p >= 0.999:
        return layer
    if p <= 0.001:
        return None
    w, h = layer.size
    mask = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(mask)
    span = 180 - 2 * ARC_GAP
    # PIL measures from three o'clock; the artwork is measured from twelve.
    if side == "left":
        end = 270 - ARC_GAP
        d.pieslice([-w, -h, w * 2, h * 2], end - span * p, end, fill=255)
    else:
        start = -90 + ARC_GAP
        d.pieslice([-w, -h, w * 2, h * 2], start, start + span * p, fill=255)
    out = layer.copy()
    out.putalpha(ImageChops.multiply(out.getchannel("A"), mask))
    return out


def light_sweep(size, p, width=0.26):
    """A diagonal specular band crossing the mark once."""
    w, h = size
    band = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(band)
    # Travels from beyond the top-left corner to beyond the bottom-right.
    span = w * 2.4
    x = -w * 0.7 + span * p
    bw = w * width
    for i in range(int(bw)):
        k = i / bw
        v = int(255 * (1 - abs(k - 0.5) * 2) ** 1.6)
        d.line([(x + i, -h), (x + i - h * 1.6, h * 2)], fill=v)
    return band.filter(ImageFilter.GaussianBlur(w * 0.02))


def pad_boxes(bar):
    """The two lime pads on the dumbbell, located by colour."""
    r, g, b, a = bar.split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(
        ImageChops.multiply(hot(ImageChops.subtract(g, r), 60), hot(ImageChops.subtract(g, b), 60)),
        hot(a, 60))
    bb = mask.getbbox()
    if not bb:
        return []
    x0, y0, x1, y1 = bb
    mid = (x0 + x1) // 2
    out = []
    for lo, hi in ((x0, mid), (mid, x1)):
        sub = mask.crop((lo, y0, hi, y1)).getbbox()
        if not sub:
            return []
        out.append((lo + sub[0], y0 + sub[1], lo + sub[2], y0 + sub[3]))
    return out


def blink_bar(base, closes, boxes):
    """The dumbbell with its pads part shut.

    The lids are drawn in the plate's own colour sampled row by row from just
    beside each pad, rather than a flat fill, because the plate is shaded top to
    bottom and a flat grey rectangle sitting on it reads as a bug.
    """
    if (closes[0] < 0.01 and closes[1] < 0.01) or not boxes:
        return base
    im = base.copy()
    px = im.load()
    d = ImageDraw.Draw(im)
    for (x0, y0, x1, y1), c in zip(boxes, closes):
        if c < 0.01:
            continue
        drop = (y1 - y0) * 0.5 * c
        for y in range(y0 - PAD_BLEED, y1 + PAD_BLEED + 1):
            if not (y < y0 + drop or y > y1 - drop):
                continue
            yy = min(max(y, 0), im.height - 1)
            d.line([(x0 - PAD_BLEED, yy), (x1 + PAD_BLEED, yy)],
                   fill=px[max(0, x0 - 22), yy])
    return im


def clamp01(x):
    return 0.0 if x < 0 else 1.0 if x > 1 else x


def ramp(t, a, b):
    """0 before a, 1 after b, eased between."""
    if b <= a:
        return 1.0 if t >= b else 0.0
    return ease_out(clamp01((t - a) / (b - a)))


def eye_close(t):
    """How shut his eyes are at film time t, 0 open and 1 closed."""
    for at, dn, up in BLINKS:
        if at <= t < at + dn:
            return ease_out((t - at) / dn)
        if at + dn <= t < at + dn + up:
            return 1 - ease_out((t - at - dn) / up)
    return 0.0


def eye_boxes(im):
    """The two eyes in a rendered figure frame, found by colour.

    Only the head is searched. The same lime turns up on the floor line under
    him, and a bounding box taken over the whole frame quietly stretches from
    his eyes to his feet.
    """
    fx0, fy0, fx1, fy1 = im.getbbox()
    head = (fx0, fy0, fx1, fy0 + int((fy1 - fy0) * 0.20))
    r, g, b, a = im.crop(head).split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(
        ImageChops.multiply(hot(ImageChops.subtract(g, r), 40), hot(ImageChops.subtract(g, b), 40)),
        hot(a, 60))
    bb = mask.getbbox()
    if not bb:
        return None
    # He has a lime mouth as well as lime eyes, so the bounding box of all the
    # green on his face runs from his eyebrows to his chin, and a lid drawn over
    # that is a dark rectangle across the whole head. Take the topmost run of
    # green rows and nothing below it.
    hh = mask.size[1]
    rows = list(mask.resize((1, hh), Image.BOX).getdata())
    top = next((y for y in range(hh) if rows[y] > 0), None)
    if top is None:
        return None
    end = next((y for y in range(top, hh) if rows[y] == 0), hh)
    mask = mask.crop((0, top, mask.size[0], end))
    bb = mask.getbbox()
    if not bb:
        return None
    x0, y0, x1, y1 = bb
    y0 += top
    y1 += top
    mid = (x0 + x1) // 2
    out = []
    for lo, hi in ((x0, mid), (mid, x1)):
        sub = mask.crop((lo, y0 - top, hi, y1 - top)).getbbox()
        if not sub:
            return None
        out.append((head[0] + lo + sub[0], head[1] + y0 + sub[1],
                    head[0] + lo + sub[2], head[1] + y0 + sub[3]))
    return out


def blink_eyes(im, close, boxes):
    """Lids drawn over his eyes, in the visor's own colour."""
    if close < 0.01 or not boxes:
        return im
    out = im.copy()
    px = out.load()
    d = ImageDraw.Draw(out)
    # Between the eyes is clean visor. Outside them are the little dark ticks,
    # so sampling there would paint the lid the wrong grey.
    visor = px[(boxes[0][2] + boxes[1][0]) // 2, (boxes[0][1] + boxes[0][3]) // 2]
    # Just enough to swallow the eye's antialiased edge and its glow. Any more
    # and the lid paints over the visor's own outline, and the whole dark band
    # visibly grows as he blinks.
    bleed = max(2, round((boxes[0][3] - boxes[0][1]) * 0.05))
    for x0, y0, x1, y1 in boxes:
        drop = (y1 - y0) * 0.5 * close
        d.rectangle([x0 - bleed, y0 - bleed, x1 + bleed, y0 + drop], fill=visor)
        d.rectangle([x0 - bleed, y1 - drop, x1 + bleed, y1 + bleed], fill=visor)
    return out


def shot_list():
    shots = []
    for f in range(int(FIG_UNTIL * FPS)):
        t = f / FPS
        shots.append({
            "cycle": round((0.10 + t / MOVE_DUR) % 1, 6),
            "face": EYES_OPEN_AT,
            "mood": "happy" if t >= HAPPY_FROM else "neutral",
        })
    return shots


def render_figure(shots):
    tmp = Path("/tmp/unio-shots.json")
    tmp.write_text(json.dumps(shots))
    print(f"rendering {len(shots)} figure frames, this takes a few minutes")
    subprocess.run([
        "node", str(ROOT / "scripts/render-bot-film.mjs"),
        "--shots", str(tmp), "--out", str(FIG), "--size", str(RENDER),
        "--move", MOVE, "--theme", "light",
    ], check=True)


def font(size, weight="Regular"):
    try:
        f = ImageFont.truetype(SFPRO, size)
        try:
            f.set_variation_by_name(weight)
        except Exception:
            pass
        return f
    except Exception:
        return ImageFont.load_default()


def centred(d, y, text, f, fill, alpha=1.0, track=0):
    if alpha <= 0.01:
        return
    w = d.textlength(text, font=f) + track * (len(text) - 1)
    x = (W - w) / 2
    col = (fill[0], fill[1], fill[2], int(255 * alpha))
    if track:
        for ch in text:
            d.text((x, y), ch, font=f, fill=col)
            x += d.textlength(ch, font=f) + track
    else:
        d.text((x, y), text, font=f, fill=col)


def fade(im, a):
    if a >= 0.999:
        return im
    out = im.copy()
    alpha = out.getchannel("A").point(lambda v: int(v * a))
    out.putalpha(alpha)
    return out


def main():
    shots = shot_list()
    if not FIG.exists() or len(list(FIG.glob("f*.png"))) < len(shots):
        render_figure(shots)
    figs = sorted(FIG.glob("f*.png"))
    if not figs:
        sys.exit("no figure frames")

    # Portrait crop, measured off the figure's own bounding box so a change to
    # the pose cannot silently reframe him. Framed on his centre line rather
    # than on the bounding box, because Mountain Pose puts the arms out and the
    # box is then much wider than the subject: cropping to it is what made the
    # first cut a small person in a large white room.
    probe = Image.open(figs[0]).convert("RGBA")
    x0, y0, x1, y1 = probe.getbbox()
    body = y1 - y0
    cx = (x0 + x1) // 2
    half = int(body * 0.30)
    crop = (cx - half, max(0, y0 - int(body * 0.02)), cx + half, y0 + int(body * 0.40))
    fw = 940
    fh = int(fw * (crop[3] - crop[1]) / (crop[2] - crop[0]))

    arcL = Image.open(ROOT / "brand/unio-left.png").convert("RGBA")
    arcR = Image.open(ROOT / "brand/unio-right.png").convert("RGBA")
    # The bar stays at its native size until the last moment: the lids are drawn
    # at the resolution the pads were measured at, then the whole thing is scaled
    # once, so the closed edges get the same antialiasing as the artwork.
    bar_src = Image.open(ROOT / "brand/unio-bar.png").convert("RGBA")
    bar_pads = pad_boxes(bar_src)
    mark = 730
    arcL = arcL.resize((mark, mark), Image.LANCZOS)
    arcR = arcR.resize((mark, mark), Image.LANCZOS)
    mx, my = (W - mark) // 2, (H - mark) // 2

    COMP.mkdir(parents=True, exist_ok=True)
    for old in COMP.glob("*.png"):
        old.unlink()

    for i in range(N):
        t = i / FPS
        frame = Image.new("RGBA", (W, H), WHITE)

        # ---- the figure ----
        if i < len(figs):
            a_in = ramp(t, 0.0, 0.70)
            a_out = 1 - ramp(t, FIG_UNTIL - 0.5, FIG_UNTIL)
            a = a_in * a_out
            if a > 0.01:
                # He arrives rather than appears, then creeps very slightly
                # closer for the rest of the shot. The push is small enough that
                # nobody sees it happening and the shot still refuses to sit
                # still, which is the difference between calm and dead.
                settle = 1.035 - 0.035 * ease_out(clamp01(t / 0.70))
                push = 1.0 + 0.045 * clamp01(t / FIG_UNTIL)
                sc = settle * push
                w2, h2 = int(fw * sc), int(fh * sc)
                src = Image.open(figs[i]).convert("RGBA")
                src = blink_eyes(src, eye_close(t), eye_boxes(src))
                im = src.crop(crop).resize((w2, h2), Image.LANCZOS)
                frame.alpha_composite(fade(im, a), ((W - w2) // 2, (H - fh) // 2 - (h2 - fh) // 2))

        # ---- the mark assembling ----
        draw_p = ease_out(clamp01((t - DRAW_FROM) / (DRAW_TO - DRAW_FROM)))
        if draw_p > 0.001:
            layer = Image.new("RGBA", (mark, mark), (0, 0, 0, 0))
            for img, side in ((arcL, "left"), (arcR, "right")):
                piece = arc_reveal(img, side, draw_p)
                if piece is not None:
                    layer.alpha_composite(piece)

            bo = clamp01((t - BAR_FROM) / (BAR_TO - BAR_FROM))
            if bo > 0.01:
                sc = 0.5 + 0.5 * ease_out_back(bo)
                bw = max(2, int(mark * sc))
                b = blink_bar(bar_src, pad_close(t), bar_pads).resize((bw, bw), Image.LANCZOS)
                layer.alpha_composite(fade(b, min(1.0, bo * 2.0)), ((mark - bw) // 2, (mark - bw) // 2))

            sp = clamp01((t - SWEEP_FROM) / (SWEEP_TO - SWEEP_FROM))
            if 0.001 < sp < 0.999:
                # Clipped to the mark's own alpha, so the light runs across the
                # artwork instead of across the white behind it.
                shine = Image.new("RGBA", (mark, mark), (255, 255, 255, 255))
                band = light_sweep((mark, mark), sp)
                shine.putalpha(ImageChops.multiply(
                    ImageChops.multiply(band, layer.getchannel("A")),
                    Image.new("L", (mark, mark), 120)))
                layer.alpha_composite(shine)

            # The whole mark takes the knock when the dumbbell lands, which is
            # what sells it as one object rather than a picture being built.
            knock = 0.0
            if BAR_TO - 0.12 <= t < BAR_TO + 0.34:
                knock = math.sin(math.pi * (t - (BAR_TO - 0.12)) / 0.46) * 0.022
            ms = int(mark * (1 + knock))
            frame.alpha_composite(layer.resize((ms, ms), Image.LANCZOS),
                                  (mx - (ms - mark) // 2, my - (ms - mark) // 2))

        frame.convert("RGB").save(COMP / f"c{i:04d}.png")

    encode()


def encode():
    import imageio_ffmpeg
    exe = imageio_ffmpeg.get_ffmpeg_exe()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([
        exe, "-y", "-framerate", str(FPS), "-i", str(COMP / "c%04d.png"),
        "-c:v", "libx264", "-preset", "slow", "-crf", "17",
        # yuv420p and even dimensions, or half the places you post it will
        # refuse the file or show a green channel.
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        str(OUT),
    ], check=True, capture_output=True)
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB, {N} frames at {FPS}fps)")


if __name__ == "__main__":
    main()
