#!/usr/bin/env python3
"""Builds the Unio announcement film.

    python3 scripts/make-brand-film.py

Renders the app's own figure through scripts/render-bot-film.mjs, composites him
onto white with the copy, closes on the logo assembling itself, and encodes an
mp4. Nothing here is generated by a model: the character is our rig and the logo
is our artwork, so every frame is exactly the thing that ships.

The outro is the app's real boot animation, slowed down. The mark is a blue arc
and a coral arc closing into one ring around a dumbbell, which is the product's
whole argument stated in a shape, so the film ends by making that shape rather
than by fading up a finished logo.
"""
import json
import math
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "brand/film/figure"
COMP = ROOT / "brand/film/comp"
OUT = ROOT / "brand/film/unio-announce.mp4"

W, H = 1080, 1920            # 9:16
FPS = 30
SECONDS = 10.0
N = int(SECONDS * FPS)

WHITE = (255, 255, 255, 255)
INK = (17, 19, 24, 255)
MUTED = (110, 116, 128, 255)

MOVE = "Mountain Pose"
MOVE_DUR = 6.4
# The blink is drawn here, not asked of the rig.
#
# The rig knows two eyes, open and closed, and switches between them on a 4.3
# second clock. Filmed, that is not a blink: it is the eyes teleporting shut for
# six frames and teleporting back, and it reads as a glitch because there is no
# frame in between. So the rig is held permanently open and the lids are drawn
# over the eyes here, which gives real in-between frames and exact control.
#
# Down fast, up slower, the way an eye actually moves, and the whole thing is
# over in a quarter of a second with almost none of it spent shut.
BLINKS = [(1.35, 0.09, 0.17), (2.90, 0.09, 0.17), (4.25, 0.08, 0.16), (5.45, 0.09, 0.17)]
EYES_OPEN_AT = 1.0           # a face clock nowhere near the rig's own blink
# He keeps one face for the whole film. The rig's happy eyes are an upward arc
# and the neutral ones are vertical bars, and there is no shape in between, so
# switching read as a glitch however it was timed. Mo: "remove the upside down
# U, just keep him blinking the whole time."
MOOD = "neutral"
# Coming out of a blink the eyes flare, which is the moment Mo picked out of the
# Higgsfield pass and wanted in the source rather than bolted on afterwards.
GLOW_LEN = 0.55

FIG_UNTIL = 6.4              # the figure is on screen until here
# Full body, not a portrait. Mo: "in the beginning we should just show his whole
# body." A 9:16 frame is the right shape for a standing figure anyway.
FIG_SCALE = 0.62             # of the frame height, head to feet
FIG_TOP = 0.10               # where his head starts, as a fraction of the frame

# He speaks, in the app's own bubble. Not a caption: the same white bubble with
# the notch on the corner nearest him, the same small COACH label, and the same
# green caret typing the line out a character at a time. Copying the app's own
# furniture is the cheapest way for a film to look like the product rather than
# like an advert for it.
# He has a name now. The app's bubble still says Coach; this is the film.
BOT_NAME = "UNIO"
SAY = "Who am I training with you today?"
SAY_FROM = 1.05              # the bubble arrives
SAY_TYPED = 2.75             # the last character lands
SAY_UNTIL = 5.95             # it starts leaving
# No copy. Mo is adding his own, so the film is picture only and every second
# has to be carried by movement instead of by a sentence.
LINES = []

# The mark does not swing in any more, it draws itself on: both arcs start at
# the top and race round to meet at the bottom. That is the same gesture as the
# progress rings on the dashboard filling up, which makes the logo assemble the
# way the product works rather than the way a logo usually appears.
DRAW_FROM, DRAW_TO = 6.20, 7.75
BAR_FROM, BAR_TO = 7.68, 8.24
SWEEP_FROM, SWEEP_TO = 8.55, 9.45     # a specular band crossing the finished mark

# The end card. Set under the mark once it has finished assembling, in the app's
# own face, with the space above it left clear for anything Mo lays over the top.
END_LINE = "Train together."
END_FROM = 8.85

SFPRO = "/System/Library/Fonts/SFNS.ttf"

# The two green pads on the dumbbell, measured off unio-bar.png by colour rather
# than guessed, in that file's own 853px space. They are tall vertical lime bars,
# which is the exact shape the rig draws his open eyes as, so the mark can blink
# with his face. Closing them is what turns a logo into the character.
# Found by colour when the film is built, not written down here. These were
# hardcoded against the old raster mark and silently pointed at empty plate the
# moment the artwork was redrawn.
PAD_BLEED = 8
BAR_PX = 853
# When the mark blinks, and which pads. (start, length, left, right)
MARK_BLINKS = [(8.42, 0.20, 1, 1), (9.20, 0.26, 0, 1)]
# The figure is rendered far larger than it is shown, because the shot is a
# portrait and the rig draws a whole standing body: at 1080 his head is about a
# hundred pixels tall, and cropping to it means upscaling the one part of the
# frame everything else is arranged around. Rendering at 2160 and cropping down
# keeps the eyes sharp, which is the entire reason for the shot.
RENDER = 2160


def ease_out(t):
    return 1 - (1 - t) ** 3


def smooth(t):
    """Ease in and out, symmetrically.

    The draw-on used ease_out, which is most of its travel in the first third
    and then a long crawl. On a stroke that is racing round a circle that does
    not read as easing, it reads as the animation giving up, so the sweep gets a
    curve that accelerates and decelerates by the same amount.
    """
    t = clamp01(t)
    return t * t * (3 - 2 * t)


def ease_out_back(t, k=1.70158):
    t -= 1
    return t * t * ((k + 1) * t + k) + 1


def pad_close(t):
    """How shut each green pad is at film time t, 0 open and 1 closed."""
    out = [0.0, 0.0]
    for at, span, l, r in MARK_BLINKS:
        if at <= t < at + span:
            # down and back up, so a blink is a movement rather than a cut
            k = (t - at) / span
            shut = math.sin(math.pi * k) ** 0.65
            out[0] = max(out[0], shut * l)
            out[1] = max(out[1], shut * r)
    return out


# Where the mark's arcs start and finish, clockwise from twelve o'clock, and the
# 2.4 degrees of clear air either side of the join. Has to agree with
# scripts/make-logo.py, which is where the artwork is drawn.
ARC_GAP = 2.4
# The stroke has round caps, and a cap bulges half a stroke-width PAST the end of
# the path it sits on. A wedge mask cut at exactly the end angle therefore slices
# through the middle of that cap and leaves a square end, which snaps to round
# the instant the reveal completes. Mo saw it: "it stops here and then it
# glitches and connects." Padding the wedge by the cap's own angular size at both
# ends means the caps are never cut and there is nothing to snap to.
# asin((stroke/2) / R) in degrees, with a little margin.
ARC_CAP = math.degrees(math.asin((116.39 / 2) / 441.81)) + 1.2


def arc_reveal(layer, side, p):
    """One arc, drawn on from the top by fraction p.

    A pie wedge from the centre does the cutting, because the arc is a ring
    around that same centre. Two things it cannot do on its own, both of which
    were visible on screen:

    The leading end. A wedge only ever cuts a straight radial line, so the end
    that is growing is a chevron for the entire reveal and then snaps round the
    instant it finishes. The fix is to union a circle the width of the stroke
    onto the mask at the leading end, which uncovers a round end out of the
    artwork that is already there.

    The edge quality. PIL fills shapes without antialiasing, so the cut is a
    stair and it crawls frame to frame. The mask is built at SS times size and
    scaled down, which is the cheapest antialiasing there is.
    """
    if p >= 0.999:
        return layer
    if p <= 0.001:
        return None
    w, h = layer.size
    SS = 4
    W2, H2 = w * SS, h * SS
    mask = Image.new("L", (W2, H2), 0)
    d = ImageDraw.Draw(mask)
    span = 180 - 2 * ARC_GAP
    # PIL measures from three o'clock; the artwork is measured from twelve.
    if side == "left":
        edge = (270 - ARC_GAP) - span * p
        d.pieslice([-W2, -H2, W2 * 2, H2 * 2], edge - ARC_CAP, 270 - ARC_GAP + ARC_CAP, fill=255)
    else:
        edge = (-90 + ARC_GAP) + span * p
        d.pieslice([-W2, -H2, W2 * 2, H2 * 2], -90 + ARC_GAP - ARC_CAP, edge + ARC_CAP, fill=255)

    # The round end, placed on the ring's centreline at the angle just reached.
    k = W2 / 1024.0
    r_ring, r_cap = 441.81 * k, (116.39 / 2) * k
    cx, cy = W2 / 2, H2 / 2
    ex = cx + r_ring * math.cos(math.radians(edge))
    ey = cy + r_ring * math.sin(math.radians(edge))
    d.ellipse([ex - r_cap, ey - r_cap, ex + r_cap, ey + r_cap], fill=255)

    mask = mask.resize((w, h), Image.LANCZOS)
    out = layer.copy()
    out.putalpha(ImageChops.multiply(out.getchannel("A"), mask))
    return out


def light_sweep(size, p, width=0.26):
    """A diagonal specular band crossing the mark once."""
    w, h = size
    band = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(band)
    # Travels from beyond the top-left corner to beyond the bottom-right.
    span = w * 2.4
    x = -w * 0.7 + span * p
    bw = w * width
    for i in range(int(bw)):
        k = i / bw
        v = int(255 * (1 - abs(k - 0.5) * 2) ** 1.6)
        d.line([(x + i, -h), (x + i - h * 1.6, h * 2)], fill=v)
    return band.filter(ImageFilter.GaussianBlur(w * 0.02))


# The app's bubble, measured off its CSS and scaled up for the frame. Values in
# index.html: white fill, a 10% ink hairline, radius 5px on the corner nearest
# him and 16px elsewhere, a soft low shadow, a 10px uppercase COACH label at
# .11em tracking in #8b94a3, the line at 14px/600 in #111318, and a 2px green
# caret. The film is 2.77x the app's 390px width, so everything here is that.
# The app draws this at 390px wide, and reproducing it at exactly that scale is
# technically faithful and practically useless: in a video it is a stamp under a
# full-height figure. Everything in the bubble is enlarged by BUB_SCALE so it
# reads at arm's length on a phone.
BUB_SCALE = 1.75
K = (1080 / 390) * BUB_SCALE
BUB_FILL = (255, 255, 255, 255)
BUB_EDGE = (17, 19, 24, 26)
BUB_LABEL = (139, 148, 163, 255)
BUB_INK = (17, 19, 24, 255)
BUB_CARET = (26, 163, 74, 255)


def bubble(text, shown, caret_on, fonts):
    """The bubble at its natural size, with `shown` characters typed."""
    f_who, f_line = fonts
    pad_x, pad_y = int(13 * K), int(10 * K)
    probe = ImageDraw.Draw(Image.new("RGBA", (8, 8)))
    tw = max(probe.textlength(text, font=f_line), probe.textlength(BOT_NAME, font=f_who))
    caret_w = int(2 * K)
    w = int(tw) + pad_x * 2 + caret_w + int(3 * K)
    line_h = int(f_line.size * 1.34)
    who_h = int(f_who.size * 1.5)
    h = pad_y * 2 + who_h + line_h

    im = Image.new("RGBA", (w + int(20 * K), h + int(20 * K)), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    box = [int(4 * K), int(2 * K), int(4 * K) + w, int(2 * K) + h]
    # The notch is the top-left corner, because the bubble hangs below him and a
    # tail pointing down would read as the floor talking.
    d.rounded_rectangle(box, radius=int(16 * K), fill=BUB_FILL, outline=BUB_EDGE, width=max(1, int(K)))
    d.rounded_rectangle([box[0], box[1], box[0] + int(30 * K), box[1] + int(30 * K)],
                        radius=int(5 * K), fill=BUB_FILL)

    tx, ty = box[0] + pad_x, box[1] + pad_y
    # Tracked out by hand: Pillow has no letter-spacing.
    lx = tx
    for ch in BOT_NAME:
        d.text((lx, ty), ch, font=f_who, fill=BUB_LABEL)
        lx += probe.textlength(ch, font=f_who) + 1.1 * K * 1.0
    ly = ty + who_h
    said = text[:shown]
    d.text((tx, ly), said, font=f_line, fill=BUB_INK)
    if caret_on:
        cx = tx + probe.textlength(said, font=f_line) + int(2 * K)
        d.rectangle([cx, ly + int(2 * K), cx + caret_w, ly + int(f_line.size * 1.0)], fill=BUB_CARET)
    return im


def neutral_floor(im, y0, body):
    """The rig's ground shadow is drawn in the accent lime.

    Under the figure in the app that is a deliberate tint. Scaled into a 9:16
    frame it becomes a hard green line running edge to edge under his feet,
    which reads as a stray stroke rather than as a shadow, so it is recoloured
    to a neutral. Only the strip below his knees is touched, which keeps his
    eyes, the other lime thing on screen, out of it.
    """
    top = int(y0 + body * 0.86)
    box = (0, top, im.width, im.height)
    strip = im.crop(box)
    r, g, b, a = strip.split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(hot(ImageChops.subtract(g, r), 25), hot(ImageChops.subtract(g, b), 25))
    grey = Image.new("RGBA", strip.size, (74, 80, 88, 0))
    grey.putalpha(a)
    lit = Image.composite(grey, strip, mask)

    # The shadow is wider than the frame, so its soft ends are cropped off and
    # what is left is a straight rule under his feet. Fading it toward the edges
    # gives it back an end, inside the frame, where it can be seen.
    w = strip.width
    ramp_px = w * 0.22
    fall = Image.new("L", (w, 1), 0)
    fp = fall.load()
    for x in range(w):
        e = min(x, w - 1 - x)
        fp[x, 0] = 255 if e > ramp_px else int(255 * (e / ramp_px) ** 1.4)
    fall = fall.resize(strip.size)
    # Only the shadow fades; his feet keep their own alpha.
    faded = ImageChops.multiply(lit.getchannel("A"), fall)
    lit.putalpha(Image.composite(faded, lit.getchannel("A"), mask))

    out = im.copy()
    out.paste(lit, box)
    return out


def soft_shadow(im, blur, dy, opacity):
    """The bubble's own drop shadow, from its alpha."""
    w, h = im.size
    sh = Image.new("RGBA", (w, h + dy), (0, 0, 0, 0))
    a = im.getchannel("A").point(lambda v: int(v * opacity))
    tint = Image.new("RGBA", (w, h), (11, 13, 17, 0))
    tint.putalpha(a)
    sh.alpha_composite(tint, (0, dy))
    return sh.filter(ImageFilter.GaussianBlur(blur))


def pad_boxes(bar):
    """The two lime pads on the dumbbell, located by colour."""
    r, g, b, a = bar.split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(
        ImageChops.multiply(hot(ImageChops.subtract(g, r), 60), hot(ImageChops.subtract(g, b), 60)),
        hot(a, 60))
    bb = mask.getbbox()
    if not bb:
        return []
    x0, y0, x1, y1 = bb
    mid = (x0 + x1) // 2
    out = []
    for lo, hi in ((x0, mid), (mid, x1)):
        sub = mask.crop((lo, y0, hi, y1)).getbbox()
        if not sub:
            return []
        out.append((lo + sub[0], y0 + sub[1], lo + sub[2], y0 + sub[3]))
    return out


def blink_bar(base, closes, boxes):
    """The dumbbell with its pads part shut.

    The lids are drawn in the plate's own colour sampled row by row from just
    beside each pad, rather than a flat fill, because the plate is shaded top to
    bottom and a flat grey rectangle sitting on it reads as a bug.
    """
    if (closes[0] < 0.01 and closes[1] < 0.01) or not boxes:
        return base
    im = base.copy()
    px = im.load()
    d = ImageDraw.Draw(im)
    for (x0, y0, x1, y1), c in zip(boxes, closes):
        if c < 0.01:
            continue
        drop = (y1 - y0) * 0.5 * c
        for y in range(y0 - PAD_BLEED, y1 + PAD_BLEED + 1):
            if not (y < y0 + drop or y > y1 - drop):
                continue
            yy = min(max(y, 0), im.height - 1)
            d.line([(x0 - PAD_BLEED, yy), (x1 + PAD_BLEED, yy)],
                   fill=px[max(0, x0 - 22), yy])
    return im


def clamp01(x):
    return 0.0 if x < 0 else 1.0 if x > 1 else x


def ramp(t, a, b):
    """0 before a, 1 after b, eased between."""
    if b <= a:
        return 1.0 if t >= b else 0.0
    return ease_out(clamp01((t - a) / (b - a)))


def eye_close(t):
    """How shut his eyes are at film time t, 0 open and 1 closed."""
    for at, dn, up in BLINKS:
        if at <= t < at + dn:
            return ease_out((t - at) / dn)
        if at + dn <= t < at + dn + up:
            return 1 - ease_out((t - at - dn) / up)
    return 0.0


def eye_flare(t):
    """How lit his eyes are, 0 to 1. Rises as the lids open and decays after."""
    out = 0.0
    for at, dn, up in BLINKS:
        start = at + dn
        if start <= t < start + GLOW_LEN:
            k = (t - start) / GLOW_LEN
            # up fast with the lids, then a slow falloff
            out = max(out, (min(1.0, k / 0.28) if k < 0.28 else (1 - (k - 0.28) / 0.72) ** 1.5))
    return out


def glow_eyes(im, boxes, amount):
    """A lime bloom over the eyes, drawn from their own shape and blurred."""
    if amount < 0.02 or not boxes:
        return im
    w, h = im.size
    lay = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(lay)
    for x0, y0, x1, y1 in boxes:
        pad = (y1 - y0) * 0.16
        d.rounded_rectangle([x0 - pad, y0 - pad, x1 + pad, y1 + pad],
                            radius=(x1 - x0) / 2 + pad, fill=255)
    lay = lay.filter(ImageFilter.GaussianBlur((boxes[0][3] - boxes[0][1]) * 0.42))
    glow = Image.new("RGBA", (w, h), (168, 255, 0, 0))
    glow.putalpha(lay.point(lambda v: int(v * 0.85 * amount)))
    out = im.copy()
    out.alpha_composite(glow)
    return out


def eye_boxes(im):
    """The two eyes in a rendered figure frame, found by colour.

    Only the head is searched. The same lime turns up on the floor line under
    him, and a bounding box taken over the whole frame quietly stretches from
    his eyes to his feet.
    """
    fx0, fy0, fx1, fy1 = im.getbbox()
    head = (fx0, fy0, fx1, fy0 + int((fy1 - fy0) * 0.20))
    r, g, b, a = im.crop(head).split()
    hot = lambda ch, t: ch.point(lambda v: 255 if v > t else 0)
    mask = ImageChops.multiply(
        ImageChops.multiply(hot(ImageChops.subtract(g, r), 40), hot(ImageChops.subtract(g, b), 40)),
        hot(a, 60))
    bb = mask.getbbox()
    if not bb:
        return None
    # He has a lime mouth as well as lime eyes, so the bounding box of all the
    # green on his face runs from his eyebrows to his chin, and a lid drawn over
    # that is a dark rectangle across the whole head. Take the topmost run of
    # green rows and nothing below it.
    hh = mask.size[1]
    rows = list(mask.resize((1, hh), Image.BOX).getdata())
    top = next((y for y in range(hh) if rows[y] > 0), None)
    if top is None:
        return None
    end = next((y for y in range(top, hh) if rows[y] == 0), hh)
    mask = mask.crop((0, top, mask.size[0], end))
    bb = mask.getbbox()
    if not bb:
        return None
    x0, y0, x1, y1 = bb
    y0 += top
    y1 += top
    mid = (x0 + x1) // 2
    out = []
    for lo, hi in ((x0, mid), (mid, x1)):
        sub = mask.crop((lo, y0 - top, hi, y1 - top)).getbbox()
        if not sub:
            return None
        out.append((head[0] + lo + sub[0], head[1] + y0 + sub[1],
                    head[0] + lo + sub[2], head[1] + y0 + sub[3]))
    return out


def blink_eyes(im, close, boxes):
    """Lids drawn over his eyes, in the visor's own colour."""
    if close < 0.01 or not boxes:
        return im
    out = im.copy()
    px = out.load()
    d = ImageDraw.Draw(out)
    # Between the eyes is clean visor. Outside them are the little dark ticks,
    # so sampling there would paint the lid the wrong grey.
    visor = px[(boxes[0][2] + boxes[1][0]) // 2, (boxes[0][1] + boxes[0][3]) // 2]
    # Just enough to swallow the eye's antialiased edge and its glow. Any more
    # and the lid paints over the visor's own outline, and the whole dark band
    # visibly grows as he blinks.
    bleed = max(2, round((boxes[0][3] - boxes[0][1]) * 0.05))
    for x0, y0, x1, y1 in boxes:
        drop = (y1 - y0) * 0.5 * close
        d.rectangle([x0 - bleed, y0 - bleed, x1 + bleed, y0 + drop], fill=visor)
        d.rectangle([x0 - bleed, y1 - drop, x1 + bleed, y1 + bleed], fill=visor)
    return out


def shot_list():
    shots = []
    for f in range(int(FIG_UNTIL * FPS)):
        t = f / FPS
        shots.append({
            "cycle": round((0.10 + t / MOVE_DUR) % 1, 6),
            "face": EYES_OPEN_AT,
            "mood": MOOD,
        })
    return shots


def render_figure(shots):
    tmp = Path("/tmp/unio-shots.json")
    tmp.write_text(json.dumps(shots))
    print(f"rendering {len(shots)} figure frames, this takes a few minutes")
    subprocess.run([
        "node", str(ROOT / "scripts/render-bot-film.mjs"),
        "--shots", str(tmp), "--out", str(FIG), "--size", str(RENDER),
        "--move", MOVE, "--theme", "light",
    ], check=True)


def font(size, weight="Regular"):
    try:
        f = ImageFont.truetype(SFPRO, size)
        try:
            f.set_variation_by_name(weight)
        except Exception:
            pass
        return f
    except Exception:
        return ImageFont.load_default()


def centred(d, y, text, f, fill, alpha=1.0, track=0):
    if alpha <= 0.01:
        return
    w = d.textlength(text, font=f) + track * (len(text) - 1)
    x = (W - w) / 2
    col = (fill[0], fill[1], fill[2], int(255 * alpha))
    if track:
        for ch in text:
            d.text((x, y), ch, font=f, fill=col)
            x += d.textlength(ch, font=f) + track
    else:
        d.text((x, y), text, font=f, fill=col)


def fade(im, a):
    if a >= 0.999:
        return im
    out = im.copy()
    alpha = out.getchannel("A").point(lambda v: int(v * a))
    out.putalpha(alpha)
    return out


def main():
    shots = shot_list()
    if not FIG.exists() or len(list(FIG.glob("f*.png"))) < len(shots):
        render_figure(shots)
    figs = sorted(FIG.glob("f*.png"))
    if not figs:
        sys.exit("no figure frames")

    # Whole body, placed rather than cropped. The bounding box includes the soft
    # floor shadow, which is far wider than he is, so the scale is taken from his
    # HEIGHT and the horizontal centre from his torso: sizing off the box would
    # shrink him to fit a shadow.
    probe = Image.open(figs[0]).convert("RGBA")
    x0, y0, x1, y1 = probe.getbbox()
    body = y1 - y0
    fscale = (H * FIG_SCALE) / body
    fw = int(probe.width * fscale)
    fh = int(probe.height * fscale)
    # Where the whole scaled canvas has to sit for his head to land on FIG_TOP.
    f_left = (W - fw) // 2
    f_top = int(H * FIG_TOP) - int(y0 * fscale)

    arcL = Image.open(ROOT / "brand/unio-left.png").convert("RGBA")
    arcR = Image.open(ROOT / "brand/unio-right.png").convert("RGBA")
    # The bar stays at its native size until the last moment: the lids are drawn
    # at the resolution the pads were measured at, then the whole thing is scaled
    # once, so the closed edges get the same antialiasing as the artwork.
    bar_src = Image.open(ROOT / "brand/unio-bar.png").convert("RGBA")
    bar_pads = pad_boxes(bar_src)
    mark = 730
    arcL = arcL.resize((mark, mark), Image.LANCZOS)
    arcR = arcR.resize((mark, mark), Image.LANCZOS)
    mx, my = (W - mark) // 2, (H - mark) // 2

    f_end = font(74, "Semibold")
    f_who = font(int(10 * K), "Heavy")
    f_line = font(int(14 * K), "Semibold")
    bub_y = int(H * 0.795)
    # Measured at full length and shrunk to fit, rather than trusting a scale
    # factor to be right: at 1.75 this line came out 1216px wide in a 1080 frame
    # and was clipped at both ends. Now any line Mo writes fits or is made to.
    BUB_MAX = W - 2 * 46
    natural = bubble(SAY, len(SAY), False, (f_who, f_line)).width if SAY else 1
    bub_fit = min(1.0, BUB_MAX / natural)

    COMP.mkdir(parents=True, exist_ok=True)
    for old in COMP.glob("*.png"):
        old.unlink()

    for i in range(N):
        t = i / FPS
        frame = Image.new("RGBA", (W, H), WHITE)

        # ---- the figure ----
        if i < len(figs):
            a_in = ramp(t, 0.0, 0.70)
            a_out = 1 - ramp(t, FIG_UNTIL - 0.5, FIG_UNTIL)
            a = a_in * a_out
            if a > 0.01:
                # He arrives rather than appears, then creeps very slightly
                # closer for the rest of the shot. The push is small enough that
                # nobody sees it happening and the shot still refuses to sit
                # still, which is the difference between calm and dead.
                settle = 1.030 - 0.030 * ease_out(clamp01(t / 0.70))
                push = 1.0 + 0.030 * clamp01(t / FIG_UNTIL)
                sc = settle * push
                w2, h2 = int(fw * sc), int(fh * sc)
                src = Image.open(figs[i]).convert("RGBA")
                src = neutral_floor(src, y0, body)
                boxes = eye_boxes(src)
                src = blink_eyes(src, eye_close(t), boxes)
                src = glow_eyes(src, boxes, eye_flare(t))
                im = src.resize((w2, h2), Image.LANCZOS)
                # Scaling about the centre of where he already sits, so the push
                # does not walk him across the frame.
                frame.alpha_composite(fade(im, a),
                                      (f_left - (w2 - fw) // 2, f_top - (h2 - fh) // 2))

        # ---- he speaks ----
        if SAY and SAY_FROM <= t < SAY_UNTIL + 0.45:
            grow = ease_out(clamp01((t - SAY_FROM) / 0.30))
            gone = ramp(t, SAY_UNTIL, SAY_UNTIL + 0.45)
            ba = grow * (1 - gone)
            if ba > 0.01:
                typed = clamp01((t - SAY_FROM - 0.18) / max(0.01, SAY_TYPED - SAY_FROM - 0.18))
                shown = int(len(SAY) * typed)
                # The caret blinks while he types and goes the moment he stops,
                # which is exactly what typeQuip does in the app.
                caret = shown < len(SAY) and int(t * 2.2) % 2 == 0
                bub = bubble(SAY, shown, caret, (f_who, f_line))
                # It arrives from slightly below and small, like the app's quipIn.
                sc = (0.94 + 0.06 * grow) * bub_fit
                bw, bh = int(bub.width * sc), int(bub.height * sc)
                b = bub.resize((bw, bh), Image.LANCZOS)
                bx = (W - bw) // 2
                by = bub_y + int(14 * (1 - grow))
                frame.alpha_composite(fade(soft_shadow(b, 12, 10, 0.28), ba), (bx, by))
                frame.alpha_composite(fade(b, ba), (bx, by))

        # ---- the mark assembling ----
        draw_p = smooth((t - DRAW_FROM) / (DRAW_TO - DRAW_FROM))
        if draw_p > 0.001:
            layer = Image.new("RGBA", (mark, mark), (0, 0, 0, 0))
            for img, side in ((arcL, "left"), (arcR, "right")):
                piece = arc_reveal(img, side, draw_p)
                if piece is not None:
                    layer.alpha_composite(piece)

            bo = clamp01((t - BAR_FROM) / (BAR_TO - BAR_FROM))
            if bo > 0.01:
                sc = 0.5 + 0.5 * ease_out_back(bo)
                bw = max(2, int(mark * sc))
                b = blink_bar(bar_src, pad_close(t), bar_pads).resize((bw, bw), Image.LANCZOS)
                layer.alpha_composite(fade(b, min(1.0, bo * 2.0)), ((mark - bw) // 2, (mark - bw) // 2))

            sp = clamp01((t - SWEEP_FROM) / (SWEEP_TO - SWEEP_FROM))
            if 0.001 < sp < 0.999:
                # Clipped to the mark's own alpha, so the light runs across the
                # artwork instead of across the white behind it.
                shine = Image.new("RGBA", (mark, mark), (255, 255, 255, 255))
                band = light_sweep((mark, mark), sp)
                shine.putalpha(ImageChops.multiply(
                    ImageChops.multiply(band, layer.getchannel("A")),
                    Image.new("L", (mark, mark), 120)))
                layer.alpha_composite(shine)

            # The whole mark takes the knock when the dumbbell lands, which is
            # what sells it as one object rather than a picture being built.
            knock = 0.0
            if BAR_TO - 0.12 <= t < BAR_TO + 0.34:
                knock = math.sin(math.pi * (t - (BAR_TO - 0.12)) / 0.46) * 0.022
            ms = int(mark * (1 + knock))
            frame.alpha_composite(layer.resize((ms, ms), Image.LANCZOS),
                                  (mx - (ms - mark) // 2, my - (ms - mark) // 2))

            ea = ramp(t, END_FROM, END_FROM + 0.55)
            if ea > 0.01:
                d = ImageDraw.Draw(frame)
                rise = int(16 * (1 - ea))
                centred(d, my + mark + int(104) + rise, END_LINE, f_end, INK, ea)

        frame.convert("RGB").save(COMP / f"c{i:04d}.png")

    encode()


def encode():
    import imageio_ffmpeg
    exe = imageio_ffmpeg.get_ffmpeg_exe()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([
        exe, "-y", "-framerate", str(FPS), "-i", str(COMP / "c%04d.png"),
        "-c:v", "libx264", "-preset", "slow", "-crf", "17",
        # yuv420p and even dimensions, or half the places you post it will
        # refuse the file or show a green channel.
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        str(OUT),
    ], check=True, capture_output=True)
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB, {N} frames at {FPS}fps)")


if __name__ == "__main__":
    main()
