// Normalized bounding boxes of every muscle the Rive body asset can draw, per artboard.
// GENERATED by extract-muscle-bounds.html (open it over a local static server; it uses the
// Canvas2D Rive build, isolates one muscle at a time, reads the pixels back and prints
// BOUNDS_JSON). Regenerate whenever assets/human_anatomy_advanced_v3.0.riv changes.
//
// Coordinates are fractions of the artboard ([x0, y0, x1, y1], 0..1). `all` is the union
// box; `left` and `right` are the two halves for muscles the figure draws on both sides
// of the body (viewer left / viewer right), null otherwise. A muscle missing from an
// artboard is not drawn on that view (lats are back-only, abs front-only, and so on).

export const MUSCLE_BOUNDS = {
  "Male-Front": {
    artboard: [178, 490],
    muscles: {
      trapezius: { all: [0.3364, 0.1511, 0.6789, 0.1856], left: [0.3364, 0.1522, 0.4404, 0.1856], right: [0.5749, 0.1511, 0.6789, 0.1844] },
      pectoralisMajor: { all: [0.2385, 0.19, 0.7768, 0.2844], left: [0.2385, 0.19, 0.4985, 0.2844], right: [0.5199, 0.19, 0.7768, 0.2844] },
      deltoids: { all: [0.1651, 0.1811, 0.8532, 0.2678], left: [0.1651, 0.1811, 0.3119, 0.2678], right: [0.7034, 0.1811, 0.8532, 0.2678] },
      rectusAbdominis: { all: [0.4128, 0.2811, 0.6024, 0.4844], left: null, right: null },
      externalObliques: { all: [0.2813, 0.2611, 0.737, 0.4411], left: [0.2813, 0.2611, 0.4037, 0.4411], right: [0.6116, 0.2611, 0.737, 0.4411] },
      biceps: { all: [0.1804, 0.2489, 0.8379, 0.3522], left: [0.1804, 0.2489, 0.2722, 0.3522], right: [0.7462, 0.2489, 0.8379, 0.3522] },
      brachialis: { all: [0.156, 0.2511, 0.8624, 0.3522], left: [0.156, 0.2511, 0.2324, 0.3522], right: [0.789, 0.2511, 0.8624, 0.3522] },
      brachioradialis: { all: [0.1101, 0.3456, 0.9083, 0.4811], left: [0.1101, 0.3456, 0.1988, 0.4811], right: [0.8196, 0.3456, 0.9083, 0.4811] },
      extensorCarpiUlnaris: { all: [0.0887, 0.3833, 0.9297, 0.48], left: [0.0887, 0.3833, 0.1346, 0.48], right: [0.8838, 0.3844, 0.9297, 0.48] },
      flexorCarpiRadialis: { all: [0.208, 0.3589, 0.8073, 0.3956], left: [0.208, 0.3589, 0.2324, 0.3956], right: [0.7829, 0.3589, 0.8073, 0.3956] },
      sartorius: { all: [0.3547, 0.4322, 0.6575, 0.6044], left: [0.3547, 0.4322, 0.4618, 0.6033], right: [0.5505, 0.4322, 0.6575, 0.6044] },
      rectusFemoris: { all: [0.2569, 0.4211, 0.7584, 0.6367], left: [0.2569, 0.4211, 0.3945, 0.6367], right: [0.6239, 0.4211, 0.7584, 0.6367] },
      vastusMedialis: { all: [0.3639, 0.5322, 0.6514, 0.6711], left: [0.3639, 0.5322, 0.4465, 0.6711], right: [0.5688, 0.5322, 0.6514, 0.6711] },
      vastusLateralis: { all: [0.2538, 0.5211, 0.7615, 0.6522], left: [0.2538, 0.5211, 0.3394, 0.6522], right: [0.6789, 0.5211, 0.7615, 0.6522] },
      tibialisAnterior: { all: [0.2813, 0.7011, 0.737, 0.8878], left: [0.2813, 0.7011, 0.3547, 0.8878], right: [0.6606, 0.7011, 0.737, 0.8878] },
      soleus: { all: [0.37, 0.8067, 0.6483, 0.8867], left: [0.37, 0.8067, 0.3976, 0.8856], right: [0.6208, 0.8067, 0.6483, 0.8867] },
      gastrocnemius: { all: [0.37, 0.7056, 0.6483, 0.8344], left: [0.37, 0.7056, 0.4373, 0.8344], right: [0.581, 0.7056, 0.6483, 0.8344] },
    },
  },
  "Male-Back": {
    artboard: [178, 490],
    muscles: {
      flexorCarpiUlnaris: { all: [0.0673, 0.3522, 0.9358, 0.4511], left: [0.0673, 0.3522, 0.1284, 0.4511], right: [0.8716, 0.3522, 0.9358, 0.4511] },
      posteriorDeltoid: { all: [0.1346, 0.1911, 0.8716, 0.27], left: [0.1346, 0.1911, 0.2966, 0.27], right: [0.7095, 0.1911, 0.8716, 0.27] },
      tricepsBrachii: { all: [0.1131, 0.2511, 0.893, 0.3567], left: [0.1131, 0.2511, 0.2446, 0.3544], right: [0.7615, 0.2533, 0.893, 0.3567] },
      teresMajor: { all: [0.2324, 0.2122, 0.7768, 0.2744], left: [0.2324, 0.2122, 0.4098, 0.2744], right: [0.6024, 0.2122, 0.7768, 0.2744] },
      latissimusDorsi: { all: [0.2538, 0.26, 0.7554, 0.3622], left: [0.2538, 0.26, 0.4679, 0.3611], right: [0.5413, 0.2611, 0.7554, 0.3622] },
      gluteusMaximus: { all: [0.2599, 0.43, 0.7462, 0.5489], left: [0.2599, 0.43, 0.4924, 0.5478], right: [0.5138, 0.4311, 0.7462, 0.5489] },
      bicepsFemoris: { all: [0.2599, 0.5489, 0.7462, 0.6967], left: [0.2599, 0.5489, 0.3639, 0.6967], right: [0.6422, 0.5489, 0.7462, 0.6967] },
      semitendinosus: { all: [0.3517, 0.5422, 0.6544, 0.6978], left: [0.3517, 0.5422, 0.4343, 0.6978], right: [0.5749, 0.5422, 0.6544, 0.6978] },
      adductorMagnus: { all: [0.422, 0.5244, 0.5841, 0.6256], left: [0.422, 0.5244, 0.4893, 0.6256], right: [0.5168, 0.5256, 0.5841, 0.6256] },
      erectorSpinae: { all: [0.3394, 0.3533, 0.6697, 0.4167], left: [0.3394, 0.3533, 0.4648, 0.4156], right: [0.5443, 0.3544, 0.6697, 0.4167] },
      trapezius: { all: [0.2813, 0.1222, 0.7248, 0.3033], left: [0.2813, 0.1222, 0.4893, 0.3022], right: [0.5168, 0.1233, 0.7248, 0.3033] },
      brachioradialis: { all: [0.0917, 0.3544, 0.9113, 0.47], left: [0.0917, 0.3544, 0.1927, 0.47], right: [0.8104, 0.3544, 0.9113, 0.4689] },
      extensorCarpiUlnaris: { all: [0.0428, 0.37, 0.9602, 0.4922], left: [0.0428, 0.37, 0.0917, 0.4922], right: [0.9144, 0.37, 0.9602, 0.4922] },
      gluteusMedius: { all: [0.2508, 0.4167, 0.7584, 0.5344], left: [0.2508, 0.4167, 0.422, 0.5333], right: [0.5872, 0.4178, 0.7584, 0.5344] },
      soleus: { all: [0.263, 0.8044, 0.7431, 0.9033], left: [0.263, 0.8044, 0.3364, 0.9033], right: [0.6697, 0.8044, 0.7431, 0.9022] },
      gastrocnemius: { all: [0.2416, 0.6667, 0.7645, 0.8156], left: [0.2416, 0.6667, 0.4067, 0.8156], right: [0.5994, 0.6667, 0.7645, 0.8156] },
    },
  },
  "Female-Front": {
    artboard: [178, 490],
    muscles: {
      sternocleidomastoid: { all: [0.4312, 0.1367, 0.5841, 0.1989], left: [0.4312, 0.1367, 0.4924, 0.1989], right: [0.5229, 0.1367, 0.5841, 0.1989] },
      trapezius: { all: [0.3394, 0.1644, 0.6758, 0.1944], left: [0.3394, 0.1644, 0.4343, 0.1944], right: [0.581, 0.1644, 0.6758, 0.1944] },
      pectoralisMajor: { all: [0.2569, 0.1989, 0.7584, 0.2989], left: [0.2569, 0.1989, 0.4924, 0.2989], right: [0.5229, 0.1989, 0.7584, 0.2989] },
      deltoids: { all: [0.1774, 0.1922, 0.8379, 0.2756], left: [0.1774, 0.1933, 0.3333, 0.2756], right: [0.682, 0.1922, 0.8379, 0.2756] },
      rectusAbdominis: { all: [0.4159, 0.2956, 0.5994, 0.4967], left: null, right: null },
      externalObliques: { all: [0.2936, 0.28, 0.7217, 0.4578], left: [0.2936, 0.28, 0.3976, 0.4578], right: [0.6177, 0.28, 0.7217, 0.4578] },
      biceps: { all: [0.1743, 0.2678, 0.8379, 0.3711], left: [0.1743, 0.2678, 0.2661, 0.3711], right: [0.7462, 0.2678, 0.8379, 0.3711] },
      brachialis: { all: [0.1498, 0.2689, 0.8654, 0.37], left: [0.1498, 0.27, 0.2232, 0.37], right: [0.789, 0.2689, 0.8654, 0.37] },
      brachioradialis: { all: [0.104, 0.35, 0.9083, 0.4722], left: [0.104, 0.35, 0.1804, 0.4722], right: [0.8318, 0.35, 0.9083, 0.4722] },
      extensorCarpiUlnaris: { all: [0.0826, 0.3767, 0.9297, 0.4733], left: [0.0826, 0.3767, 0.1315, 0.4733], right: [0.8838, 0.3767, 0.9297, 0.4733] },
      flexorCarpiRadialis: { all: [0.1957, 0.37, 0.8165, 0.4067], left: [0.1957, 0.37, 0.2232, 0.4067], right: [0.789, 0.3711, 0.8165, 0.4067] },
      sartorius: { all: [0.318, 0.44, 0.6942, 0.6144], left: [0.318, 0.44, 0.4709, 0.6133], right: [0.5413, 0.4411, 0.6942, 0.6144] },
      rectusFemoris: { all: [0.2294, 0.4278, 0.7859, 0.6678], left: [0.2294, 0.4289, 0.3976, 0.6678], right: [0.6177, 0.4278, 0.7859, 0.6678] },
      vastusMedialis: { all: [0.37, 0.5289, 0.6453, 0.6833], left: [0.37, 0.53, 0.4557, 0.6833], right: [0.5596, 0.5289, 0.6453, 0.6833] },
      vastusLateralis: { all: [0.2294, 0.5333, 0.7859, 0.6733], left: [0.2294, 0.5333, 0.3486, 0.6733], right: [0.6636, 0.5333, 0.7859, 0.6733] },
      tibialisAnterior: { all: [0.2905, 0.7167, 0.7217, 0.8967], left: [0.2905, 0.7167, 0.3853, 0.8967], right: [0.6269, 0.7167, 0.7217, 0.8967] },
      soleus: { all: [0.3945, 0.8211, 0.6177, 0.8956], left: [0.3945, 0.8211, 0.419, 0.8956], right: [0.5902, 0.8211, 0.6177, 0.8956] },
      gastrocnemius: { all: [0.3945, 0.7356, 0.6177, 0.8411], left: [0.3945, 0.7356, 0.4465, 0.8411], right: [0.5657, 0.7356, 0.6177, 0.8411] },
    },
  },
  "Female-Back": {
    artboard: [178, 490],
    muscles: {
      flexorCarpiUlnaris: { all: [0.0948, 0.3467, 0.9052, 0.4367], left: [0.0948, 0.3467, 0.156, 0.4367], right: [0.844, 0.3467, 0.9052, 0.4367] },
      posteriorDeltoid: { all: [0.1713, 0.1889, 0.8318, 0.2689], left: [0.1713, 0.1889, 0.3333, 0.2689], right: [0.6697, 0.1889, 0.8318, 0.2689] },
      tricepsBrachii: { all: [0.1529, 0.2422, 0.844, 0.3378], left: [0.1529, 0.2422, 0.2722, 0.3378], right: [0.7278, 0.2433, 0.844, 0.3378] },
      teresMajor: { all: [0.2538, 0.2089, 0.7431, 0.2722], left: [0.2538, 0.2089, 0.4251, 0.2711], right: [0.5749, 0.21, 0.7431, 0.2722] },
      latissimusDorsi: { all: [0.2813, 0.2622, 0.7156, 0.3578], left: [0.2813, 0.2622, 0.4801, 0.3578], right: [0.5199, 0.2622, 0.7156, 0.3578] },
      gluteusMaximus: { all: [0.263, 0.4189, 0.737, 0.5333], left: [0.263, 0.4189, 0.4862, 0.5322], right: [0.5138, 0.42, 0.737, 0.5333] },
      bicepsFemoris: { all: [0.2844, 0.5344, 0.7156, 0.7], left: [0.2844, 0.5344, 0.367, 0.7], right: [0.633, 0.5344, 0.7156, 0.7] },
      semitendinosus: { all: [0.3639, 0.53, 0.633, 0.6911], left: [0.3639, 0.53, 0.4343, 0.6911], right: [0.5627, 0.53, 0.633, 0.6911] },
      adductorMagnus: { all: [0.4128, 0.5167, 0.5872, 0.6256], left: [0.4128, 0.5167, 0.4771, 0.6256], right: [0.5199, 0.5167, 0.5872, 0.6244] },
      erectorSpinae: { all: [0.3761, 0.35, 0.6239, 0.4133], left: [0.3761, 0.35, 0.4832, 0.4133], right: [0.5168, 0.35, 0.6239, 0.4133] },
      trapezius: { all: [0.3119, 0.1344, 0.685, 0.2989], left: [0.3119, 0.1344, 0.4862, 0.2989], right: [0.5107, 0.1344, 0.685, 0.2989] },
      brachioradialis: { all: [0.1223, 0.3422, 0.8777, 0.4544], left: [0.1223, 0.3422, 0.2263, 0.4544], right: [0.7737, 0.3422, 0.8777, 0.4544] },
      extensorCarpiUlnaris: { all: [0.0734, 0.3678, 0.9266, 0.4644], left: [0.0734, 0.3678, 0.1193, 0.4644], right: [0.8777, 0.3689, 0.9266, 0.4644] },
      gluteusMedius: { all: [0.2477, 0.4078, 0.7523, 0.5144], left: [0.2477, 0.4078, 0.419, 0.5133], right: [0.5841, 0.4089, 0.7523, 0.5144] },
      soleus: { all: [0.2905, 0.8033, 0.7095, 0.8756], left: [0.2905, 0.8033, 0.3517, 0.8756], right: [0.6483, 0.8044, 0.7095, 0.8756] },
      gastrocnemius: { all: [0.2722, 0.6689, 0.7248, 0.8144], left: [0.2722, 0.6689, 0.4251, 0.8144], right: [0.5749, 0.6689, 0.7248, 0.8144] },
    },
  },
};

/** Views ("Front" | "Back") that draw this muscle for the given sex ("Male" | "Female"). */
export function viewsFor(muscle, sex) {
  return ["Front", "Back"].filter((v) => MUSCLE_BOUNDS[`${sex}-${v}`]?.muscles[muscle]);
}

/**
 * Box to zoom to for a muscle on one artboard: the tapped side for bilateral muscles
 * (side is "left" | "right" in viewer terms), the whole muscle otherwise. Null when the
 * artboard does not draw it.
 */
export function boundsFor(artboardName, muscle, side) {
  const m = MUSCLE_BOUNDS[artboardName]?.muscles[muscle];
  if (!m) return null;
  if (side && m[side]) return m[side];
  return m.all;
}
